import type { ContentItem } from './types'

// All imageUrl values reference /flyers/* — served from public/flyers/
// Real info: Fascinoma (fascinoma.space · @fascinoma_mx) + Club Japan (Monterrey 56, Roma Norte · @japan_cdmx)

export const MOCK_ITEMS: ContentItem[] = [

  // ─── EVENTOS ─────────────────────────────────────────────────────────────

  {
    id: 'ev-fascinoma-2026',
    slug: 'fascinoma-2026-cdmx-outdoor',
    type: 'evento',
    title: 'FASCiNOMA 2026',
    subtitle: 'Espacio al aire libre CDMX · Dub · Techno · Jungle',
    excerpt: 'La décima edición del festival más importante de música de club en México regresa a CDMX con un espacio al aire libre sin precedentes. Tres días de dub techno, ambient, jungle y drum and bass con los mejores artistas del mundo.',
    vibe: 7,
    genres: ['techno-raw', 'downtempo', 'drum-and-bass', 'ambient', 'dubstep', 'ukg'],
    tags: ['festival', 'open-air'],
    imageUrl: '/flyers/rf-001.jpg',
    publishedAt: '2026-04-01T10:00:00',
    date: '2026-05-22T14:00:00',
    endDate: '2026-05-24T23:59:00',
    expiresAt: '2026-05-25T06:00:00',
    venue: 'Espacio TBA — CDMX',
    venueCity: 'CDMX',
    artists: ['Surgeon', 'Donato Dozzy', 'Sicaria', 're:ni', 'Debit (live)', 'Vladimir Ivkovic', 'Intrusion / Echospace (live)', 'Alpha & Omega (live)', 'Sully', 'Dave P'],
    price: '$1,800 – $4,500',
    ticketUrl: 'https://www.passline.com/eventos/fascinoma',
    editorial: true,
  },

  {
    id: 'ev-fascinoma-workshop',
    slug: 'fascinoma-2026-workshop-donato-dozzy',
    type: 'evento',
    title: 'FASCiNOMA — Workshop con Donato Dozzy',
    subtitle: 'Modular · Dub Techno · Composición Hipnótica',
    excerpt: 'El productor italiano y maestro del dub techno hipnótico abre una sesión cerrada de preguntas y conversación sobre su proceso creativo, su relación con el silencio y la repetición.',
    vibe: 3,
    genres: ['techno-raw', 'ambient-techno', 'idm', 'downtempo'],
    tags: ['workshop', 'modular'],
    imageUrl: '/flyers/rf-002.jpg',
    publishedAt: '2026-04-15T09:00:00',
    date: '2026-05-21T16:00:00',
    endDate: '2026-05-21T20:00:00',
    expiresAt: '2026-05-21T20:00:00',
    venue: 'Espacio FASCiNOMA Lab',
    venueCity: 'CDMX',
    artists: ['Donato Dozzy'],
    price: 'Acreditación festival',
    ticketUrl: 'https://www.fascinoma.space',
  },

  {
    id: 'ev-japan-industrial',
    slug: 'japan-cdmx-industrial-night-abr26',
    type: 'evento',
    title: 'CLUB JAPAN — INDUSTRIAL NIGHT',
    subtitle: 'EBM · Dark Electro · Hard Techno · Roma Norte',
    excerpt: 'Una de las noches más oscuras del Japan: cuatro horas de EBM clásico, dark electro y hard techno en el basement de Monterrey 56. Sin concesiones.',
    vibe: 10,
    genres: ['industrial', 'dark-techno', 'hard-techno', 'wave'],
    tags: ['club-night', 'vinyl-only', 'anl'],
    imageUrl: '/flyers/rf-003.jpg',
    publishedAt: '2026-04-11T14:00:00',
    date: '2026-04-19T23:00:00',
    endDate: '2026-04-20T05:00:00',
    expiresAt: '2026-04-20T06:00:00',
    venue: 'Club Japan',
    venueCity: 'CDMX · Monterrey 56, Roma Norte',
    artists: ['Rat Pack Crew', 'La Mystica', 'BLAKK'],
    price: '$250',
    ticketUrl: 'https://www.passline.com/sitio/japan-cdmx',
    editorial: true,
  },

  {
    id: 'ev-siete-catorce-live',
    slug: 'siete-catorce-live-foro-indie-rocks-abr26',
    type: 'evento',
    title: 'SIETE CATORCE',
    subtitle: 'Live A/V · Obra nueva · Foro Indie Rocks',
    excerpt: 'El productor oaxaqueño presenta su nuevo proyecto audiovisual en vivo: síntesis modular, procesamiento en tiempo real y el Popocatépetl como eje narrativo.',
    vibe: 9,
    genres: ['techno-raw', 'electronica', 'noise', 'ambient-techno'],
    tags: ['live', 'anl'],
    imageUrl: '/flyers/rf-004.jpg',
    publishedAt: '2026-04-10T10:00:00',
    date: '2026-04-18T22:00:00',
    endDate: '2026-04-19T05:00:00',
    expiresAt: '2026-04-19T06:00:00',
    venue: 'Foro Indie Rocks',
    venueCity: 'CDMX',
    artists: ['Siete Catorce'],
    price: '$350',
    ticketUrl: '#',
    editorial: true,
  },

  {
    id: 'ev-atrevida-naafi',
    slug: 'atrevida-naafi-alicia-abr26',
    type: 'evento',
    title: 'ATREVIDA',
    subtitle: 'N.A.A.F.I. · Multiforo Alicia',
    excerpt: 'La fiesta mensual de N.A.A.F.I. toma Multiforo Alicia. Una noche segura y de cero tolerancia a la violencia.',
    vibe: 8,
    genres: ['ballroom', 'breaks', 'jersey-club', 'footwork'],
    tags: ['lgbtq', 'club-night', 'feminist'],
    imageUrl: '/flyers/rf-005.jpg',
    publishedAt: '2026-04-08T12:00:00',
    date: '2026-04-19T22:00:00',
    endDate: '2026-04-20T04:00:00',
    expiresAt: '2026-04-20T05:00:00',
    venue: 'Multiforo Alicia',
    venueCity: 'CDMX',
    artists: ['Cøsmetic', 'Fausto', 'Girl Ultra'],
    price: '$200',
    ticketUrl: '#',
    editorial: true,
  },

  {
    id: 'ev-japan-rat-pack',
    slug: 'club-japan-rat-pack-crew-may26',
    type: 'evento',
    title: 'CLUB JAPAN × RAT PACK CREW',
    subtitle: 'Techno · Breaks · Rave · All Night',
    excerpt: 'Los Rat Pack Crew toman el control del Japan para una noche de techno crudo y breaks que no para hasta que sale el sol sobre Roma Norte.',
    vibe: 9,
    genres: ['techno-raw', 'breaks', 'industrial', 'electro'],
    tags: ['rave', 'anl', 'club-night'],
    imageUrl: '/flyers/rf-006.jpg',
    publishedAt: '2026-04-14T10:00:00',
    date: '2026-05-02T23:00:00',
    endDate: '2026-05-03T06:00:00',
    expiresAt: '2026-05-03T07:00:00',
    venue: 'Club Japan',
    venueCity: 'CDMX · Monterrey 56, Roma Norte',
    artists: ['Rat Pack Crew', 'BLAKK', 'Morbid Machines'],
    price: '$300',
    ticketUrl: 'https://www.passline.com/sitio/japan-cdmx',
  },

  {
    id: 'ev-python-cosmetic',
    slug: 'dj-python-b2b-cosmetic-el-bajo-abr26',
    type: 'evento',
    title: 'DJ PYTHON b2b CØSMETIC',
    subtitle: 'Viernes Oscuro @ El Bajo',
    excerpt: 'El neoyorquino del reggaeton electrónico y la reina del hard techno se encuentran en El Bajo. Una sesión que nadie esperaba.',
    vibe: 7,
    genres: ['deconstructed', 'hard-techno', 'techno-raw'],
    tags: ['b2b', 'club-night'],
    imageUrl: '/flyers/rf-007.jpg',
    publishedAt: '2026-04-12T15:00:00',
    date: '2026-04-25T23:00:00',
    endDate: '2026-04-26T06:00:00',
    expiresAt: '2026-04-26T07:00:00',
    venue: 'El Bajo',
    venueCity: 'CDMX',
    artists: ['DJ Python', 'Cøsmetic'],
    price: '$400',
    ticketUrl: '#',
    editorial: true,
  },

  {
    id: 'ev-fauna-d1',
    slug: 'fauna-festival-dia1-abr26',
    type: 'evento',
    title: 'FAUNA FESTIVAL — Día 1',
    subtitle: 'Parque Bicentenario · Ambient · Downtempo',
    excerpt: 'El festival de música electrónica al aire libre regresa con su edición primaveral. Día 1: ambient, downtempo y techno hipnótico.',
    vibe: 5,
    genres: ['ambient', 'downtempo', 'techno-raw', 'organic-house'],
    tags: ['festival', 'open-air', 'day-party'],
    imageUrl: '/flyers/rf-008.jpg',
    publishedAt: '2026-04-01T10:00:00',
    date: '2026-04-26T14:00:00',
    endDate: '2026-04-26T23:59:00',
    expiresAt: '2026-04-27T01:00:00',
    venue: 'Parque Bicentenario',
    venueCity: 'CDMX',
    artists: ['Atemporal', 'Hiele', 'PLVS VLTRA'],
    price: '$650',
    ticketUrl: '#',
  },

  {
    id: 'ev-fauna-d2',
    slug: 'fauna-festival-dia2-abr26',
    type: 'evento',
    title: 'FAUNA FESTIVAL — Día 2',
    subtitle: 'Parque Bicentenario · Peak Techno · Hard',
    excerpt: 'Día 2 del Fauna: el piso de baile se intensifica con peak time techno, hard techno y un cierre b2b sorpresa.',
    vibe: 9,
    genres: ['peak-techno', 'hard-techno', 'tech-house'],
    tags: ['festival', 'open-air', 'b2b'],
    imageUrl: '/flyers/rf-009.jpg',
    publishedAt: '2026-04-01T10:00:00',
    date: '2026-04-27T14:00:00',
    endDate: '2026-04-27T23:59:00',
    expiresAt: '2026-04-28T01:00:00',
    venue: 'Parque Bicentenario',
    venueCity: 'CDMX',
    artists: ['Siete Catorce', 'La Mystica', 'Fausto'],
    price: '$650',
    ticketUrl: '#',
    editorial: true,
  },

  {
    id: 'ev-japan-hardtechno-may',
    slug: 'club-japan-hard-techno-residency-may26',
    type: 'evento',
    title: 'CLUB JAPAN — Hard Techno Residency',
    subtitle: 'Cøsmetic en residencia · Mayo 2026',
    excerpt: 'Primera fecha de la residencia mensual de Cøsmetic en el Japan. Tres horas de hard techno de CDMX seguidas de invitados sorpresa.',
    vibe: 10,
    genres: ['hard-techno', 'dark-techno', 'industrial'],
    tags: ['residency', 'club-night', 'anl'],
    imageUrl: '/flyers/rf-010.jpg',
    publishedAt: '2026-04-15T10:00:00',
    date: '2026-05-08T23:00:00',
    endDate: '2026-05-09T06:00:00',
    expiresAt: '2026-05-09T07:00:00',
    venue: 'Club Japan',
    venueCity: 'CDMX · Monterrey 56, Roma Norte',
    artists: ['Cøsmetic', 'BLAKK'],
    price: '$300',
    ticketUrl: 'https://www.passline.com/sitio/japan-cdmx',
  },

  {
    id: 'ev-naafi-showcase',
    slug: 'naafi-showcase-treinta-tres-may26',
    type: 'evento',
    title: 'N.A.A.F.I. SHOWCASE',
    subtitle: 'Treinta y Tres — All Night Long',
    excerpt: 'El colectivo más influyente del underground global presenta a su roster completo. De las 10pm al amanecer.',
    vibe: 9,
    genres: ['deconstructed', 'ballroom', 'footwork', 'breaks'],
    tags: ['showcase', 'label-night', 'anl'],
    imageUrl: '/flyers/rf-011.jpg',
    publishedAt: '2026-04-15T09:00:00',
    date: '2026-05-09T22:00:00',
    endDate: '2026-05-10T06:00:00',
    expiresAt: '2026-05-10T07:00:00',
    venue: 'Treinta y Tres',
    venueCity: 'CDMX',
    artists: ['Cøsmetic', 'Fausto', 'Girl Ultra (live)', 'Cid Rim'],
    price: '$500',
    ticketUrl: '#',
    editorial: true,
  },

  {
    id: 'ev-vinyl-only',
    slug: 'vinyl-only-bajo-mundo-may26',
    type: 'evento',
    title: 'VINYL ONLY NIGHT',
    subtitle: 'El Bajo Mundo GDL · Deep House · Soul · Jazz',
    excerpt: 'Una noche de sólo acetato. Deep house, broken beat, nu-jazz y soul, tocado de manera analógica de inicio a fin.',
    vibe: 4,
    genres: ['deep-house', 'jazz', 'nu-disco', 'soul'],
    tags: ['club-night', 'vinyl-only'],
    imageUrl: '/flyers/rf-012.jpg',
    publishedAt: '2026-04-13T18:00:00',
    date: '2026-05-16T22:00:00',
    endDate: '2026-05-17T05:00:00',
    expiresAt: '2026-05-17T06:00:00',
    venue: 'El Bajo Mundo',
    venueCity: 'GDL',
    artists: ['Aquiles Navarro', 'DJ Toro'],
    price: '$150',
    ticketUrl: '#',
  },

  {
    id: 'ev-charla-genero',
    slug: 'charla-genero-electronica-may26',
    type: 'evento',
    title: 'Género y Electrónica en México',
    subtitle: 'Charla · Centro Cultural España',
    excerpt: 'Mesa redonda sobre la participación de mujeres y personas no binarias en la escena. Con Cøsmetic, re:ni (vía videollamada) y Daniela Ríos.',
    vibe: 3,
    genres: ['electronica'],
    tags: ['charla', 'lgbtq', 'feminist', 'free', 'community'],
    imageUrl: '/flyers/rf-013.jpg',
    publishedAt: '2026-04-14T11:00:00',
    date: '2026-05-03T17:00:00',
    endDate: '2026-05-03T20:00:00',
    expiresAt: '2026-05-03T20:00:00',
    venue: 'Centro Cultural España',
    venueCity: 'CDMX',
    price: 'Entrada libre',
    ticketUrl: '#',
  },

  // ─── MIXES ───────────────────────────────────────────────────────────────

  {
    id: 'mx-001',
    slug: 'espectro-mix-001-siete-catorce',
    type: 'mix',
    title: 'ESPECTRO MIX 001',
    subtitle: 'Siete Catorce',
    excerpt: '90 minutos de techno hipnótico, noise industrial y texturas volcánicas desde las faldas del Popocatépetl.',
    vibe: 9,
    genres: ['techno-raw', 'noise', 'industrial', 'dark-techno'],
    tags: ['radio'],
    imageUrl: '/flyers/rf-014.jpg',
    publishedAt: '2026-04-15T08:00:00',
    date: '2026-04-15T08:00:00',
    expiresAt: '2026-06-15T00:00:00',
    duration: '1:28:44',
    mixUrl: '#',
    author: 'Siete Catorce',
    editorial: true,
  },

  {
    id: 'mx-002',
    slug: 'espectro-mix-002-rat-pack',
    type: 'mix',
    title: 'ESPECTRO MIX 002',
    subtitle: 'Rat Pack Crew',
    excerpt: '70 minutos de breaks duros, electro oscuro y referencias directas al rave de los 90. Crudo y sin filtro.',
    vibe: 8,
    genres: ['breaks', 'electro', 'industrial', 'techno-raw'],
    tags: ['radio'],
    imageUrl: '/flyers/rf-015.jpg',
    publishedAt: '2026-04-12T09:00:00',
    date: '2026-04-12T09:00:00',
    expiresAt: '2026-06-12T00:00:00',
    duration: '1:08:17',
    mixUrl: '#',
    author: 'Rat Pack Crew',
    editorial: true,
  },

  {
    id: 'mx-003',
    slug: 'espectro-mix-003-donato-dozzy',
    type: 'mix',
    title: 'ESPECTRO MIX 003',
    subtitle: 'Donato Dozzy — Previo FASCiNOMA',
    excerpt: 'El maestro italiano del dub techno hipnótico entrega un mix exclusivo para Espectro FM como anticipo de su presentación en FASCiNOMA 2026.',
    vibe: 5,
    genres: ['techno-raw', 'ambient-techno', 'downtempo', 'minimal'],
    tags: ['radio'],
    imageUrl: '/flyers/rf-016.jpg',
    publishedAt: '2026-04-10T10:00:00',
    date: '2026-04-10T10:00:00',
    expiresAt: '2026-06-10T00:00:00',
    duration: '1:52:10',
    mixUrl: '#',
    author: 'Donato Dozzy',
  },

  {
    id: 'mx-004',
    slug: 'japan-cdmx-mixcloud-best-of',
    type: 'mix',
    title: 'Japan CDMX Mixcloud — Best Of 2025',
    subtitle: 'Archivo oficial · @japan_cdmx',
    excerpt: 'Selección de las mejores sesiones grabadas en vivo en Club Japan durante 2025: hard techno, EBM, dark electro y techno hipnótico. El archivo definitivo del venue.',
    vibe: 9,
    genres: ['hard-techno', 'dark-techno', 'industrial', 'ebm'],
    tags: ['live', 'radio'],
    imageUrl: '/flyers/rf-017.jpg',
    publishedAt: '2026-04-08T16:00:00',
    date: '2026-04-08T16:00:00',
    expiresAt: '2026-07-08T00:00:00',
    duration: '3:44:00',
    mixUrl: 'https://www.mixcloud.com/JAPANCDMX/',
    author: 'Club Japan',
  },

  {
    id: 'mx-005',
    slug: 'surgeon-fascinoma-previo',
    type: 'mix',
    title: 'Surgeon — Live at FASCiNOMA 2016',
    subtitle: 'Archivo · Primera edición del festival',
    excerpt: 'Recuperamos el set en vivo de Surgeon en la primera edición de FASCiNOMA en Puebla, 2016. El momento en que el festival definió su identidad.',
    vibe: 8,
    genres: ['techno-peak', 'dark-techno', 'industrial'],
    tags: ['live'],
    imageUrl: '/flyers/rf-018.jpg',
    publishedAt: '2026-04-05T12:00:00',
    date: '2026-04-05T12:00:00',
    expiresAt: '2026-06-05T00:00:00',
    duration: '1:38:00',
    mixUrl: '#',
    author: 'Surgeon',
  },

  {
    id: 'mx-006',
    slug: 'aquiles-navarro-ambient-ritual-vol3',
    type: 'mix',
    title: 'Ritual Acústico — Vol. III',
    subtitle: 'Aquiles Navarro',
    excerpt: 'Tercer volumen: vientos, síntesis granular y grabaciones de campo del Istmo de Tehuantepec.',
    vibe: 1,
    genres: ['ambient', 'organic-house', 'lo-fi', 'downtempo'],
    tags: [],
    imageUrl: '/flyers/rf-019.jpg',
    publishedAt: '2026-04-03T09:00:00',
    date: '2026-04-03T09:00:00',
    expiresAt: '2026-07-03T00:00:00',
    duration: '44:17',
    mixUrl: '#',
    author: 'Aquiles Navarro',
  },

  {
    id: 'mx-007',
    slug: 're-ni-fascinoma-advance',
    type: 'mix',
    title: "re:ni — FASCiNOMA Advance Mix",
    subtitle: 'Drum and Bass · UK Garage · UKG',
    excerpt: 'La DJ londinense entrega una hora de drum and bass y UK garage como anticipo de su debut en México en FASCiNOMA 2026.',
    vibe: 7,
    genres: ['drum-and-bass', 'ukg', 'breaks', 'jungle'],
    tags: ['radio'],
    imageUrl: '/flyers/rf-020.jpg',
    publishedAt: '2026-04-06T12:00:00',
    date: '2026-04-06T12:00:00',
    expiresAt: '2026-06-06T00:00:00',
    duration: '1:03:44',
    mixUrl: '#',
    author: "re:ni",
  },

  // ─── NOTICIAS ────────────────────────────────────────────────────────────

  {
    id: 'no-001',
    slug: 'fascinoma-2026-cdmx-outdoor-anuncio',
    type: 'noticia',
    title: 'FASCiNOMA 2026 confirma su regreso a CDMX con espacio al aire libre inédito',
    excerpt: 'El festival más importante de música de club en México anuncia lineup completo para su décima edición: Surgeon, Donato Dozzy, re:ni, Debit, Intrusion/Echospace, Alpha & Omega y más.',
    vibe: 7,
    genres: ['techno-raw', 'drum-and-bass', 'ambient', 'dubstep'],
    tags: ['festival'],
    imageUrl: '/flyers/rf-021.jpg',
    publishedAt: '2026-04-15T09:30:00',
    date: '2026-04-15T09:30:00',
    expiresAt: '2026-05-25T00:00:00',
    author: 'Redacción Espectro',
    readTime: 4,
    editorial: true,
  },

  {
    id: 'no-002',
    slug: 'club-japan-10-aniversario',
    type: 'noticia',
    title: 'Club Japan cumple 10 años: el sótano de Roma Norte que cambió la escena',
    excerpt: 'El venue underground en Monterrey 56 cumple una década de noches de EBM, hard techno e industrial. Un repaso de su historia y lo que viene para el aniversario.',
    vibe: 8,
    genres: ['techno-raw', 'industrial', 'dark-techno', 'hard-techno'],
    tags: ['community'],
    imageUrl: '/flyers/rf-022.jpg',
    publishedAt: '2026-04-13T10:00:00',
    date: '2026-04-13T10:00:00',
    expiresAt: '2026-05-13T00:00:00',
    author: 'Marco Reyes',
    readTime: 5,
  },

  {
    id: 'no-003',
    slug: 'naafi-showcase-berghain-anuncio',
    type: 'noticia',
    title: 'N.A.A.F.I. anuncia showcase en Berghain para junio',
    excerpt: 'El colectivo mexicano llevará a tres de sus artistas al mítico club berlinés en lo que será su presentación más importante en Europa hasta la fecha.',
    vibe: 7,
    genres: ['deconstructed', 'ballroom'],
    tags: ['showcase'],
    imageUrl: '/flyers/rf-023.jpg',
    publishedAt: '2026-04-12T09:30:00',
    date: '2026-04-12T09:30:00',
    expiresAt: '2026-05-15T00:00:00',
    author: 'Redacción Espectro',
    readTime: 3,
  },

  {
    id: 'no-004',
    slug: 'espacio-clandestino-cierra',
    type: 'noticia',
    title: 'Espacio Clandestino cierra sus puertas después de 8 años',
    excerpt: 'El venue icónico de la Colonia Guerrero anuncia su cierre definitivo. La comunidad reacciona y se organizan fiestas de despedida con parte del lineup original.',
    vibe: 4,
    genres: ['techno-raw', 'minimal'],
    tags: ['community'],
    imageUrl: '/flyers/rf-024.jpg',
    publishedAt: '2026-04-10T15:00:00',
    date: '2026-04-10T15:00:00',
    expiresAt: '2026-04-30T00:00:00',
    author: 'Marco Reyes',
    readTime: 4,
  },

  {
    id: 'no-005',
    slug: 'surgeon-primera-vez-mexico',
    type: 'noticia',
    title: 'Surgeon tocará en México por primera vez desde 2016',
    excerpt: 'El productor y DJ de Birmingham regresa a México para FASCiNOMA 2026, diez años después de su legendario set en la primera edición del festival en Puebla.',
    vibe: 8,
    genres: ['techno-peak', 'dark-techno', 'industrial'],
    tags: ['festival'],
    imageUrl: '/flyers/rf-025.jpg',
    publishedAt: '2026-04-11T10:00:00',
    date: '2026-04-11T10:00:00',
    expiresAt: '2026-05-25T00:00:00',
    author: 'Fernanda Lugo',
    readTime: 3,
  },

  // ─── REVIEWS ─────────────────────────────────────────────────────────────

  {
    id: 'rv-001',
    slug: 'review-kode9-el-under',
    type: 'review',
    title: 'Kode9 @ El Under fue un terremoto sónico',
    subtitle: 'El Under, CDMX · Abril 11, 2026',
    excerpt: 'El pionero del dubstep y fundador de Hyperdub entregó una de las noches más brutales y conceptualmente densas que hemos visto en CDMX en años recientes.',
    vibe: 8,
    genres: ['dubstep', 'ukg', 'dark-techno'],
    tags: ['club-night'],
    imageUrl: '/flyers/rf-026.jpg',
    publishedAt: '2026-04-13T14:00:00',
    date: '2026-04-13T14:00:00',
    expiresAt: '2026-05-13T00:00:00',
    author: 'Roberto Sánchez',
    readTime: 6,
    editorial: true,
  },

  {
    id: 'rv-002',
    slug: 'review-album-siete-catorce-volcan',
    type: 'review',
    title: 'Siete Catorce — "Volcán" (NAAFI, 2026)',
    subtitle: '8 tracks · 44 min',
    excerpt: 'El álbum más visceral de Siete Catorce. Ocho piezas que oscilan entre la belleza quebrada y el caos total, con el Popocatépetl como eje narrativo.',
    vibe: 9,
    genres: ['techno-raw', 'noise', 'electronica', 'ambient-techno'],
    tags: [],
    imageUrl: '/flyers/rf-027.jpg',
    publishedAt: '2026-04-14T09:00:00',
    date: '2026-04-14T09:00:00',
    expiresAt: '2026-06-14T00:00:00',
    author: 'Daniela Ríos',
    readTime: 8,
    editorial: true,
  },

  {
    id: 'rv-003',
    slug: 'review-club-japan-noche-tipica',
    type: 'review',
    title: 'Club Japan: una noche típica en el sótano de Roma Norte',
    subtitle: 'Crónica de venue · Monterrey 56',
    excerpt: 'Una crónica personal del Japan: el sistema de sonido brutal, la arquitectura de cemento, y por qué este venue es el lugar más honesto de la escena underground capitalina.',
    vibe: 8,
    genres: ['techno-raw', 'industrial', 'hard-techno'],
    tags: ['community'],
    imageUrl: '/flyers/rf-028.jpg',
    publishedAt: '2026-04-12T10:00:00',
    date: '2026-04-12T10:00:00',
    expiresAt: '2026-06-12T00:00:00',
    author: 'Fernanda Lugo',
    readTime: 7,
  },

  {
    id: 'rv-004',
    slug: 'review-fascinoma-2024-puebla',
    type: 'review',
    title: 'FASCiNOMA 2024 — Tres días en la Exfábrica Textil de Puebla',
    subtitle: 'Festival Review · LTJ Bukem · Ben UFO · Laurel Halo · DJ Nobu',
    excerpt: 'La edición del regreso a Puebla fue una declaración de principios: LTJ Bukem, Ben UFO, Laurel Halo, Jane Fitz y DJ Nobu en una fábrica textil del siglo XIX. FASCiNOMA encontró su alma.',
    vibe: 6,
    genres: ['drum-and-bass', 'downtempo', 'ambient', 'techno-raw'],
    tags: ['festival', 'open-air'],
    imageUrl: '/flyers/rf-029.jpg',
    publishedAt: '2026-04-07T11:00:00',
    date: '2026-04-07T11:00:00',
    expiresAt: '2026-05-07T00:00:00',
    author: 'Fernanda Lugo',
    readTime: 9,
  },

  // ─── EDITORIAL ───────────────────────────────────────────────────────────

  {
    id: 'ed-001',
    slug: 'shawn-raynaldo-club-japan-pedagogia',
    type: 'editorial',
    title: 'Club Japan y la pedagogía de la oscuridad',
    subtitle: 'Shawn Raynaldo · Substack "Sonidos Nocturnos"',
    excerpt: 'La historia del Club Japan no es solo la historia de un venue: es la historia de cómo una comunidad construyó, desde el underground y sin ningún apoyo institucional, la educación sónica de toda una generación.',
    bodyPreview: 'La primera vez que fui al Club Japan no sabía bien dónde estaba parado. Un sótano sin señalización visible en Monterrey 56, una puerta de metal sin nada que indicara lo que había adentro, y una fila de personas que obviamente sabían algo que yo no. Era 2019. Llevaba seis meses viviendo en CDMX y alguien me había mandado un flyer pixelado por Telegram.\n\nAdentro había un sistema de sonido que no había escuchado nada igual. No era la mejor tecnología del mundo — había venues en Europa con mejor equipo — pero había algo en cómo estaba calibrado, en cómo el sub pegaba exactamente en el centro del pecho, que hacía imposible no mover el cuerpo.\n\nLo que vi en el Japan esa noche, y lo que he seguido viendo en cada visita desde entonces, no es simplemente entretenimiento. Es una clase magistral de historia de la música electrónica: EBM alemán de los 80, industrial inglés, techno de Detroit mutado por manos mexicanas. Una genealogía sonora completa, transmitida no en un aula sino en un sótano oscuro a las 3 de la mañana.',
    vibe: 8,
    genres: ['techno-raw', 'industrial', 'dark-techno', 'hard-techno'],
    tags: ['community'],
    imageUrl: '/flyers/rf-030.jpg',
    publishedAt: '2026-04-15T07:00:00',
    date: '2026-04-15T07:00:00',
    expiresAt: '2026-07-15T00:00:00',
    author: 'Shawn Raynaldo',
    readTime: 14,
    editorial: true,
    pinned: true,
  },

  {
    id: 'ed-002',
    slug: 'editorial-hard-techno-moral-panic',
    type: 'editorial',
    title: 'El hard techno y el pánico moral: ¿de qué le tenemos miedo?',
    subtitle: 'Por Daniela Ríos',
    excerpt: 'El género más intenso del momento genera debates sobre accesibilidad, violencia sonora y gentrificación del underground. Una mirada sin filtros.',
    bodyPreview: 'Hay una conversación que se repite en cada esquina de la escena mexicana desde hace dos años: ¿el hard techno es demasiado agresivo? ¿Es accesible? ¿Excluye? La pregunta parece inocente, pero esconde algo más complejo: el miedo de una escena a los extremos de sí misma.\n\nEl hard techno no es un fenómeno nuevo. Sus raíces están en el techno más oscuro de Detroit y en el industrial europeo de los 90. Lo que sí es nuevo es su popularización masiva — y con ella, la llegada de públicos que no necesariamente vienen de la cultura de club que lo parió.\n\nEn Club Japan llevan años programando noches de hard techno sin que nadie se rasgue las vestiduras. La diferencia está en el contexto: un venue con historia, con comunidad, con reglas implícitas de comportamiento. El problema no es el sonido. El problema es cuando el sonido llega a espacios sin esa estructura.',
    vibe: 8,
    genres: ['hard-techno', 'dark-techno', 'industrial'],
    tags: ['community'],
    imageUrl: '/flyers/rf-031.jpg',
    publishedAt: '2026-04-12T08:00:00',
    date: '2026-04-12T08:00:00',
    expiresAt: '2026-07-12T00:00:00',
    author: 'Daniela Ríos',
    readTime: 12,
  },

  {
    id: 'ed-003',
    slug: 'shawn-raynaldo-fascinoma-diez-anos',
    type: 'editorial',
    title: 'FASCiNOMA a 10 años: el festival que apostó por la educación sonora',
    subtitle: 'Shawn Raynaldo · Substack "Sonidos Nocturnos"',
    excerpt: 'Una revisión de la primera década de FASCiNOMA: cómo un festival en una fábrica textil de Puebla se convirtió en el proyecto curatorial más importante de la música de club en México.',
    bodyPreview: 'En noviembre de 2016, en una fábrica textil restaurada a 90 minutos de Ciudad de México, algo cambió. No de inmediato — estas cosas nunca cambian de inmediato — pero en retrospectiva, la primera edición de FASCiNOMA marcó un antes y un después en la historia de los festivales de música electrónica en México.\n\nEl lineup de ese debut decía todo sobre las intenciones del equipo detrás del festival: Larry Heard, Mala, Kode 9, Dâm Funk, DeepChord, Lucy, Joey Anderson. No era una selección pensada para maximizar asistentes. Era una selección pensada para educar, para mostrar genealogías, para conectar puntos que el mainstream mexicano jamás hubiera conectado.\n\nDiez años después, esa filosofía no ha cambiado. FASCiNOMA 2026 trae a Surgeon, Donato Dozzy y Intrusion/Echospace no porque sean los nombres más reconocibles del momento, sino porque representan un hilo conductor en la historia de la música electrónica que vale la pena celebrar.',
    vibe: 6,
    genres: ['techno-raw', 'drum-and-bass', 'ambient', 'downtempo'],
    tags: ['festival', 'community'],
    imageUrl: '/flyers/rf-032.jpg',
    publishedAt: '2026-04-09T08:00:00',
    date: '2026-04-09T08:00:00',
    expiresAt: '2026-07-09T00:00:00',
    author: 'Shawn Raynaldo',
    readTime: 16,
  },

  {
    id: 'ed-004',
    slug: 'editorial-venues-cdmx-crisis',
    type: 'editorial',
    title: 'La crisis de venues en CDMX: sobrevivir o desaparecer',
    subtitle: 'Por Valeria Mora',
    excerpt: 'Con el cierre de Espacio Clandestino y rumores de que otros espacios no renovarán, ¿cómo protegemos los lugares que hacen posible la escena? Y qué pueden aprender del modelo Club Japan.',
    vibe: 4,
    genres: ['electronica', 'techno-raw'],
    tags: ['community'],
    imageUrl: '/flyers/rf-033.jpg',
    publishedAt: '2026-04-11T08:00:00',
    date: '2026-04-11T08:00:00',
    expiresAt: '2026-07-11T00:00:00',
    author: 'Valeria Mora',
    readTime: 9,
  },

  {
    id: 'ed-005',
    slug: 'shawn-raynaldo-naafi-diez-anos',
    type: 'editorial',
    title: 'N.A.A.F.I. a 10 años: el colectivo que cambió cómo suena México',
    subtitle: 'Shawn Raynaldo · Substack "Sonidos Nocturnos"',
    excerpt: 'Una revisión exhaustiva de la primera década de N.A.A.F.I.: cómo un colectivo de CDMX redefinió lo que puede significar la música electrónica latinoamericana a nivel global.',
    vibe: 7,
    genres: ['deconstructed', 'ballroom', 'footwork'],
    tags: ['community'],
    imageUrl: '/flyers/rf-034.jpg',
    publishedAt: '2026-04-07T08:00:00',
    date: '2026-04-07T08:00:00',
    expiresAt: '2026-07-07T00:00:00',
    author: 'Shawn Raynaldo',
    readTime: 18,
  },

  // ─── EVENTOS adicionales ─────────────────────────────────────────────────────

  {
    id: 'ev-stingray-313',
    slug: 'dj-stingray-313-treinta-y-tres-may26',
    type: 'evento',
    title: 'DJ STINGRAY 313',
    subtitle: 'Detroit Electro · Treinta y Tres',
    excerpt: 'El ícono del electro de Detroit llega a CDMX por primera vez en una noche que promete las rutas más oscuras del Motor City.',
    vibe: 8,
    genres: ['electro', 'techno-raw', 'industrial', 'breaks'],
    tags: ['club-night', 'anl'],
    imageUrl: '/flyers/rf-035.jpg',
    publishedAt: '2026-04-16T10:00:00',
    date: '2026-04-25T23:00:00',
    endDate: '2026-04-26T06:00:00',
    expiresAt: '2026-04-26T07:00:00',
    venue: 'Treinta y Tres',
    venueCity: 'CDMX',
    artists: ['DJ Stingray 313', 'La Mystica'],
    price: '$450',
    ticketUrl: '#',
    editorial: true,
  },

  {
    id: 'ev-cumbia-electronica',
    slug: 'noche-cumbia-electronica-alicia-may26',
    type: 'evento',
    title: 'CUMBIA ELÉCTRICA',
    subtitle: 'Multiforo Alicia · Noche de Ritmos Híbridos',
    excerpt: 'Una noche que conecta cumbia chicha, cumbia electrónica y experimentación tropical. Celebración sin apología del sincretismo sonoro mexicano.',
    vibe: 7,
    genres: ['cumbia-electronica', 'latin-electronic', 'reggaeton'],
    tags: ['club-night', 'lgbtq', 'community'],
    imageUrl: '/flyers/rf-036.jpg',
    publishedAt: '2026-04-14T09:00:00',
    date: '2026-04-26T21:00:00',
    endDate: '2026-04-27T04:00:00',
    expiresAt: '2026-04-27T05:00:00',
    venue: 'Multiforo Alicia',
    venueCity: 'CDMX',
    artists: ['Aquiles Navarro', 'Atemporal', 'DJ Toro'],
    price: '$180',
    ticketUrl: '#',
  },

  {
    id: 'ev-vladimir-ivkovic',
    slug: 'vladimir-ivkovic-el-bajo-may26',
    type: 'evento',
    title: 'VLADIMIR IVKOVIC',
    subtitle: 'El Bajo · Noche Completa',
    excerpt: 'El DJ serbio de Omoide Yokocho y Salon Des Amateurs en CDMX. Una maratón de cinco horas que abarcará ambient, kosmische, dub y techno en su forma más narrativa.',
    vibe: 4,
    genres: ['ambient-techno', 'minimal', 'techno-raw', 'downtempo'],
    tags: ['club-night', 'anl'],
    imageUrl: '/flyers/rf-037.jpg',
    publishedAt: '2026-04-15T11:00:00',
    date: '2026-05-01T22:00:00',
    endDate: '2026-05-02T05:00:00',
    expiresAt: '2026-05-02T06:00:00',
    venue: 'El Bajo',
    venueCity: 'CDMX',
    artists: ['Vladimir Ivkovic'],
    price: '$350',
    ticketUrl: '#',
    editorial: true,
  },

  {
    id: 'ev-dnb-gdl',
    slug: 'drum-bass-noche-gdl-may26',
    type: 'evento',
    title: 'SINÁPTICA — DNB NOCHE',
    subtitle: 'El Bajo Mundo · Guadalajara',
    excerpt: 'Drum and bass de todo el espectro: desde el liquid funk hasta el neurofunk más oscuro, con residents de GDL y un guest de CDMX.',
    vibe: 8,
    genres: ['drum-and-bass', 'jungle', 'breaks', 'ukg'],
    tags: ['club-night', 'rave'],
    imageUrl: '/flyers/rf-038.jpg',
    publishedAt: '2026-04-13T14:00:00',
    date: '2026-05-03T22:00:00',
    endDate: '2026-05-04T05:00:00',
    expiresAt: '2026-05-04T06:00:00',
    venue: 'El Bajo Mundo',
    venueCity: 'GDL',
    artists: ['Sully (UK)', 'Dave P', 'Colectivo Sináptica'],
    price: '$200',
    ticketUrl: '#',
  },

  {
    id: 'ev-debit-live',
    slug: 'debit-live-av-foro-indie-may26',
    type: 'evento',
    title: 'DEBIT — Live A/V',
    subtitle: 'Foro Indie Rocks · Material nuevo',
    excerpt: 'La producción en vivo más esperada del año: Debit presenta un set A/V completamente nuevo en el Foro Indie Rocks antes de su gira europea de verano.',
    vibe: 6,
    genres: ['techno-raw', 'ambient-techno', 'electronica', 'idm'],
    tags: ['live', 'club-night'],
    imageUrl: '/flyers/rf-039.jpg',
    publishedAt: '2026-04-16T10:00:00',
    date: '2026-05-07T22:00:00',
    endDate: '2026-05-08T03:00:00',
    expiresAt: '2026-05-08T04:00:00',
    venue: 'Foro Indie Rocks',
    venueCity: 'CDMX',
    artists: ['Debit (live A/V)'],
    price: '$400',
    ticketUrl: '#',
    editorial: true,
  },

  {
    id: 'ev-jardin-sonoro',
    slug: 'jardin-sonoro-parque-espana-may26',
    type: 'evento',
    title: 'JARDÍN SONORO',
    subtitle: 'Parque España · Electrónica Orgánica · Día',
    excerpt: 'Festival de un día en Parque España: música orgánica, ambient y downtempo en formato jardín. Entrada libre para la sección exterior, cuota sugerida para el escenario principal.',
    vibe: 2,
    genres: ['organic-house', 'ambient', 'lo-fi', 'downtempo', 'neo-soul'],
    tags: ['day-party', 'free', 'community', 'open-air'],
    imageUrl: '/flyers/rf-040.jpg',
    publishedAt: '2026-04-14T16:00:00',
    date: '2026-05-10T13:00:00',
    endDate: '2026-05-10T21:00:00',
    expiresAt: '2026-05-10T22:00:00',
    venue: 'Parque España',
    venueCity: 'CDMX',
    artists: ['Aquiles Navarro (live)', 'Hiele', 'Atemporal'],
    price: 'Entrada libre · $100 sugerido',
    ticketUrl: '#',
  },

  {
    id: 'ev-alpha-omega',
    slug: 'alpha-omega-live-el-bajo-may26',
    type: 'evento',
    title: 'ALPHA & OMEGA — Live Dub',
    subtitle: 'El Bajo · Dub Raíz · Sound System',
    excerpt: 'Los pioneros del dub londinense traen su sound system completo a El Bajo. Una experiencia que va más allá del concierto: una ceremonia de graves.',
    vibe: 3,
    genres: ['dub', 'ambient', 'minimal'],
    tags: ['live', 'club-night'],
    imageUrl: '/flyers/rf-041.jpg',
    publishedAt: '2026-04-12T10:00:00',
    date: '2026-05-15T21:00:00',
    endDate: '2026-05-16T02:00:00',
    expiresAt: '2026-05-16T03:00:00',
    venue: 'El Bajo',
    venueCity: 'CDMX',
    artists: ['Alpha & Omega (live)'],
    price: '$500',
    ticketUrl: '#',
    editorial: true,
  },

  {
    id: 'ev-intrusion-live',
    slug: 'intrusion-echospace-live-fascinoma-extra',
    type: 'evento',
    title: 'INTRUSION / ECHOSPACE — Noche Satélite',
    subtitle: 'Evento satélite FASCiNOMA · El Bajo',
    excerpt: 'Una noche adicional de Rod Modell en formato íntimo: el arquitecto del dub techno detroitiano presenta ambient techno en vivo en El Bajo.',
    vibe: 3,
    genres: ['techno-raw', 'ambient-techno', 'minimal', 'downtempo'],
    tags: ['live', 'club-night'],
    imageUrl: '/flyers/rf-042.jpg',
    publishedAt: '2026-04-14T09:00:00',
    date: '2026-05-21T21:00:00',
    endDate: '2026-05-22T02:00:00',
    expiresAt: '2026-05-22T03:00:00',
    venue: 'El Bajo',
    venueCity: 'CDMX',
    artists: ['Intrusion / Echospace (live)'],
    price: '$600',
    ticketUrl: '#',
    editorial: true,
  },

  {
    id: 'ev-japan-cierre-temporada',
    slug: 'club-japan-cierre-temporada-jun26',
    type: 'evento',
    title: 'CLUB JAPAN — CIERRE DE TEMPORADA',
    subtitle: 'Todos los residents · 8 horas',
    excerpt: 'El Japan cierra su temporada de primavera con todos sus residents en una noche de ocho horas. EBM, dark electro, hard techno e industrial de las 11pm al amanecer.',
    vibe: 10,
    genres: ['industrial', 'dark-techno', 'hard-techno', 'wave'],
    tags: ['club-night', 'anl', 'closing-party', 'vinyl-only'],
    imageUrl: '/flyers/rf-043.jpg',
    publishedAt: '2026-04-17T10:00:00',
    date: '2026-05-30T23:00:00',
    endDate: '2026-05-31T07:00:00',
    expiresAt: '2026-05-31T08:00:00',
    venue: 'Club Japan',
    venueCity: 'CDMX · Monterrey 56, Roma Norte',
    artists: ['Rat Pack Crew', 'La Mystica', 'BLAKK', 'Cøsmetic'],
    price: '$350',
    ticketUrl: 'https://www.passline.com/sitio/japan-cdmx',
    editorial: true,
  },

  {
    id: 'ev-gqom-fiesta',
    slug: 'gqom-afrobeats-treinta-tres-may26',
    type: 'evento',
    title: 'ISIPHUMO — GQOM / AFROBEATS',
    subtitle: 'Treinta y Tres · Sudáfrica en CDMX',
    excerpt: 'Una noche de gqom, amapiano y afrobeats que conecta la escena global de club africano con la pista de baile capitalina.',
    vibe: 9,
    genres: ['gqom', 'afrobeats', 'uk-bass', 'jersey-club'],
    tags: ['club-night', 'lgbtq'],
    imageUrl: '/flyers/rf-044.jpg',
    publishedAt: '2026-04-15T12:00:00',
    date: '2026-05-23T23:00:00',
    endDate: '2026-05-24T05:00:00',
    expiresAt: '2026-05-24T06:00:00',
    venue: 'Treinta y Tres',
    venueCity: 'CDMX',
    artists: ['Fausto', 'Cid Rim', 'Thulile Zuma (ZA)'],
    price: '$300',
    ticketUrl: '#',
  },

  // ─── MIXES adicionales ───────────────────────────────────────────────────────

  {
    id: 'mx-008',
    slug: 'espectro-mix-008-la-mystica',
    type: 'mix',
    title: 'ESPECTRO MIX 008',
    subtitle: 'La Mystica',
    excerpt: 'La residente del Japan entrega 75 minutos de EBM, dark electro y wave pensados para las horas más oscuras de la madrugada.',
    vibe: 9,
    genres: ['industrial', 'wave', 'dark-techno'],
    tags: ['radio'],
    imageUrl: '/flyers/rf-045.jpg',
    publishedAt: '2026-04-16T09:00:00',
    date: '2026-04-16T09:00:00',
    expiresAt: '2026-06-16T00:00:00',
    duration: '1:15:32',
    mixUrl: '#',
    author: 'La Mystica',
    editorial: true,
  },

  {
    id: 'mx-009',
    slug: 'espectro-mix-009-blakk',
    type: 'mix',
    title: 'ESPECTRO MIX 009',
    subtitle: 'BLAKK',
    excerpt: 'El productor y DJ de CDMX navega por techno industrial, electro y hard techno con una lógica narrativa que muy pocos manejan en la escena.',
    vibe: 9,
    genres: ['hard-techno', 'industrial', 'electro', 'dark-techno'],
    tags: ['radio'],
    imageUrl: '/flyers/rf-046.jpg',
    publishedAt: '2026-04-13T10:00:00',
    date: '2026-04-13T10:00:00',
    expiresAt: '2026-06-13T00:00:00',
    duration: '1:22:08',
    mixUrl: '#',
    author: 'BLAKK',
  },

  {
    id: 'mx-010',
    slug: 'espectro-mix-010-fausto',
    type: 'mix',
    title: 'ESPECTRO MIX 010',
    subtitle: 'Fausto — N.A.A.F.I.',
    excerpt: 'El productor de N.A.A.F.I. despliega su arsenal: deconstructed club, ballroom, footwork y Jersey club en una hora de radio sin concesiones.',
    vibe: 8,
    genres: ['deconstructed', 'ballroom', 'footwork', 'jersey-club'],
    tags: ['radio'],
    imageUrl: '/flyers/rf-047.jpg',
    publishedAt: '2026-04-09T10:00:00',
    date: '2026-04-09T10:00:00',
    expiresAt: '2026-06-09T00:00:00',
    duration: '58:41',
    mixUrl: '#',
    author: 'Fausto',
    editorial: true,
  },

  {
    id: 'mx-011',
    slug: 'vladimir-ivkovic-back-catalogue',
    type: 'mix',
    title: 'Vladimir Ivkovic — Balearic Sessions Vol. 1',
    subtitle: 'Archivo · Omoide Yokocho 2022',
    excerpt: 'Recuperamos una de las sesiones más míticas de Ivkovic: cuatro horas de ambient, kosmische y electrónica experimental desde Belgrado.',
    vibe: 3,
    genres: ['ambient-techno', 'minimal', 'downtempo', 'ambient'],
    tags: ['live'],
    imageUrl: '/flyers/rf-048.jpg',
    publishedAt: '2026-04-08T12:00:00',
    date: '2026-04-08T12:00:00',
    expiresAt: '2026-07-08T00:00:00',
    duration: '3:58:00',
    mixUrl: '#',
    author: 'Vladimir Ivkovic',
  },

  {
    id: 'mx-012',
    slug: 'espectro-mix-012-hiele',
    type: 'mix',
    title: 'ESPECTRO MIX 012',
    subtitle: 'Hiele — Techno Hipnótico',
    excerpt: 'El productor mexicano al límite más lento del techno: 80 minutos de ritmos mínimos, capas drones y texturas que disuelven el tiempo.',
    vibe: 5,
    genres: ['techno-raw', 'minimal', 'ambient-techno'],
    tags: ['radio'],
    imageUrl: '/flyers/rf-049.jpg',
    publishedAt: '2026-04-06T10:00:00',
    date: '2026-04-06T10:00:00',
    expiresAt: '2026-06-06T00:00:00',
    duration: '1:21:04',
    mixUrl: '#',
    author: 'Hiele',
  },

  {
    id: 'mx-013',
    slug: 'girl-ultra-live-set-alicia',
    type: 'mix',
    title: 'Girl Ultra — Live @ Multiforo Alicia',
    subtitle: 'Grabación en vivo · Marzo 2026',
    excerpt: 'El set en vivo de Girl Ultra en el Multiforo Alicia durante la noche de Atrevida. R&B, pop electrónico y producción hipermoderna.',
    vibe: 6,
    genres: ['rnb', 'dance-electro-pop', 'nu-disco'],
    tags: ['live', 'radio', 'lgbtq'],
    imageUrl: '/flyers/rf-050.jpg',
    publishedAt: '2026-04-04T14:00:00',
    date: '2026-04-04T14:00:00',
    expiresAt: '2026-06-04T00:00:00',
    duration: '47:20',
    mixUrl: '#',
    author: 'Girl Ultra',
    editorial: true,
  },

  {
    id: 'mx-014',
    slug: 'espectro-mix-014-atemporal',
    type: 'mix',
    title: 'ESPECTRO MIX 014',
    subtitle: 'Atemporal — Grabaciones de Campo',
    excerpt: 'El artista oaxaqueño mezcla grabaciones de campo del Istmo con síntesis modular y beats fragmentados. Una de las entregas más personales de la serie.',
    vibe: 2,
    genres: ['ambient', 'lo-fi', 'organic-house', 'electronica'],
    tags: ['radio'],
    imageUrl: '/flyers/rf-051.jpg',
    publishedAt: '2026-04-02T10:00:00',
    date: '2026-04-02T10:00:00',
    expiresAt: '2026-06-02T00:00:00',
    duration: '52:17',
    mixUrl: '#',
    author: 'Atemporal',
  },

  {
    id: 'mx-015',
    slug: 'dj-toro-cumbia-baile',
    type: 'mix',
    title: 'DJ Toro — Para El Baile Vol. 2',
    subtitle: 'Cumbia · Latin Electronic · Dance',
    excerpt: 'Segundo volumen: cumbia sintetizada, electrocumbia y ritmos latinoamericanos procesados para la pista sin perder el alma.',
    vibe: 7,
    genres: ['cumbia-electronica', 'latin-electronic', 'cumbia'],
    tags: ['radio'],
    imageUrl: '/flyers/rf-052.jpg',
    publishedAt: '2026-04-01T12:00:00',
    date: '2026-04-01T12:00:00',
    expiresAt: '2026-06-01T00:00:00',
    duration: '1:08:00',
    mixUrl: '#',
    author: 'DJ Toro',
  },

  // ─── REVIEWS adicionales ─────────────────────────────────────────────────────

  {
    id: 'rv-005',
    slug: 'review-vladimir-ivkovic-el-bajo',
    type: 'review',
    title: 'Vladimir Ivkovic convirtió El Bajo en otro tiempo',
    subtitle: 'El Bajo, CDMX · Marzo 28, 2026',
    excerpt: 'Cuatro horas y media de música que nunca tocó tierra. Ivkovic construyó un viaje desde el ambient berlinés hasta el kosmische más denso sin que nadie en la sala mirara el teléfono.',
    vibe: 4,
    genres: ['ambient-techno', 'minimal', 'downtempo'],
    tags: ['club-night'],
    imageUrl: '/flyers/rf-053.jpg',
    publishedAt: '2026-04-16T12:00:00',
    date: '2026-04-16T12:00:00',
    expiresAt: '2026-05-16T00:00:00',
    author: 'Marco Reyes',
    readTime: 5,
    editorial: true,
  },

  {
    id: 'rv-006',
    slug: 'review-cosmetic-residency-japan',
    type: 'review',
    title: 'Cøsmetic en residencia: cómo dominar un venue en 90 minutos',
    subtitle: 'Club Japan, CDMX · Abril 5, 2026',
    excerpt: 'La primera noche de la residencia de Cøsmetic en el Japan dejó en claro por qué es la DJ más importante de la escena mexicana actual. Una lección de construcción de tensión.',
    vibe: 10,
    genres: ['hard-techno', 'dark-techno', 'industrial'],
    tags: ['residency', 'club-night'],
    imageUrl: '/flyers/rf-054.jpg',
    publishedAt: '2026-04-14T11:00:00',
    date: '2026-04-14T11:00:00',
    expiresAt: '2026-05-14T00:00:00',
    author: 'Daniela Ríos',
    readTime: 6,
    editorial: true,
  },

  {
    id: 'rv-007',
    slug: 'review-aquiles-navarro-live-bicentenario',
    type: 'review',
    title: 'Aquiles Navarro en el Bicentenario: jazz como acto de desobediencia',
    subtitle: 'Parque Bicentenario, CDMX · Abril 12, 2026',
    excerpt: 'El contrabajista venezolano-estadounidense convirtió un domingo en una afirmación política. Vientos, electrónica y jazz libre ante 800 personas.',
    vibe: 3,
    genres: ['jazz', 'ambient', 'neo-soul', 'organic-house'],
    tags: ['live', 'open-air', 'community'],
    imageUrl: '/flyers/rf-055.jpg',
    publishedAt: '2026-04-13T13:00:00',
    date: '2026-04-13T13:00:00',
    expiresAt: '2026-05-13T00:00:00',
    author: 'Roberto Sánchez',
    readTime: 7,
  },

  {
    id: 'rv-008',
    slug: 'review-blakk-ep-maquina-negra',
    type: 'review',
    title: 'BLAKK — "Máquina Negra" EP (autopublicado, 2026)',
    subtitle: '5 tracks · 27 min',
    excerpt: 'El productor capitalino entrega su trabajo más maduro: cinco piezas de industrial techno tan crudas como precisas. El mejor debut extendido del año en México.',
    vibe: 9,
    genres: ['industrial', 'dark-techno', 'hard-techno'],
    tags: [],
    imageUrl: '/flyers/rf-056.jpg',
    publishedAt: '2026-04-11T09:00:00',
    date: '2026-04-11T09:00:00',
    expiresAt: '2026-06-11T00:00:00',
    author: 'Roberto Sánchez',
    readTime: 5,
  },

  {
    id: 'rv-009',
    slug: 'review-re-ni-treinta-y-tres',
    type: 'review',
    title: 're:ni en Treinta y Tres: el drum and bass como lenguaje total',
    subtitle: 'Treinta y Tres, CDMX · Febrero 14, 2026',
    excerpt: 'Su primera visita a México y dejó a toda la sala sin palabras. re:ni no solo toca drum and bass: lo disecciona, lo reconstruye y lo convierte en algo que solo ella puede hacer.',
    vibe: 7,
    genres: ['drum-and-bass', 'ukg', 'jungle', 'breaks'],
    tags: ['club-night'],
    imageUrl: '/flyers/rf-057.jpg',
    publishedAt: '2026-04-10T10:00:00',
    date: '2026-04-10T10:00:00',
    expiresAt: '2026-05-10T00:00:00',
    author: 'Fernanda Lugo',
    readTime: 6,
    editorial: true,
  },

  {
    id: 'rv-010',
    slug: 'review-atrevida-naafi-alicia-abr26',
    type: 'review',
    title: 'Atrevida N.A.A.F.I.: el piso más seguro de CDMX',
    subtitle: 'Multiforo Alicia, CDMX · Marzo 22, 2026',
    excerpt: 'La fiesta mensual de N.A.A.F.I. sigue siendo el único espacio donde la seguridad no es un añadido: es la estructura completa de la noche.',
    vibe: 8,
    genres: ['ballroom', 'jersey-club', 'footwork', 'breaks'],
    tags: ['lgbtq', 'feminist', 'club-night'],
    imageUrl: '/flyers/rf-058.jpg',
    publishedAt: '2026-04-09T14:00:00',
    date: '2026-04-09T14:00:00',
    expiresAt: '2026-05-09T00:00:00',
    author: 'Daniela Ríos',
    readTime: 5,
    editorial: true,
  },

  {
    id: 'rv-011',
    slug: 'review-alpha-omega-dub-cdmx-2025',
    type: 'review',
    title: 'Alpha & Omega en CDMX: los graves como arquitectura',
    subtitle: 'Crónica · El Bajo, CDMX · Noviembre 2025',
    excerpt: 'Recuperamos la crónica de la visita de Alpha & Omega como anticipo de su regreso en mayo. El dub más denso y espiritual que hemos visto en vivo.',
    vibe: 3,
    genres: ['dub', 'ambient', 'minimal'],
    tags: ['live'],
    imageUrl: '/flyers/rf-059.jpg',
    publishedAt: '2026-04-08T11:00:00',
    date: '2026-04-08T11:00:00',
    expiresAt: '2026-05-16T00:00:00',
    author: 'Marco Reyes',
    readTime: 8,
  },

  {
    id: 'rv-012',
    slug: 'review-fauna-festival-2025',
    type: 'review',
    title: 'Fauna 2025: cuando el parque es el instrumento',
    subtitle: 'Festival · Parque Bicentenario · Oct 2025',
    excerpt: 'La edición 2025 de Fauna redefinió lo que puede hacer un festival de día en CDMX. Crónica de un evento que tardó tres días en terminar de procesar.',
    vibe: 5,
    genres: ['ambient', 'organic-house', 'techno-raw', 'downtempo'],
    tags: ['festival', 'open-air'],
    imageUrl: '/flyers/rf-060.jpg',
    publishedAt: '2026-04-07T10:00:00',
    date: '2026-04-07T10:00:00',
    expiresAt: '2026-05-07T00:00:00',
    author: 'Valeria Mora',
    readTime: 10,
  },

  {
    id: 'rv-013',
    slug: 'review-girl-ultra-debut-album',
    type: 'review',
    title: 'Girl Ultra — "Sofía" (NAAFI, 2026)',
    subtitle: 'Álbum debut · 11 tracks · 38 min',
    excerpt: 'El álbum debut de Sofía Escobedo es una declaración de independencia: R&B que se niega a ser domesticado, con producción de Fausto y un arco emocional impecable.',
    vibe: 6,
    genres: ['rnb', 'dance-electro-pop', 'nu-disco'],
    tags: [],
    imageUrl: '/flyers/rf-061.jpg',
    publishedAt: '2026-04-06T09:00:00',
    date: '2026-04-06T09:00:00',
    expiresAt: '2026-06-06T00:00:00',
    author: 'Fernanda Lugo',
    readTime: 7,
    editorial: true,
  },

  {
    id: 'rv-014',
    slug: 'review-surgeon-fascinoma-2024',
    type: 'review',
    title: 'Surgeon en FASCiNOMA 2024: todo lo que esperabas y más',
    subtitle: 'Festival · Puebla · 2024',
    excerpt: 'Recuperamos la reseña del último paso de Surgeon por México como contexto para su regreso en 2026. Una de las actuaciones en vivo más densas que ha dado este escenario.',
    vibe: 8,
    genres: ['techno-peak', 'dark-techno', 'industrial'],
    tags: ['festival', 'live'],
    imageUrl: '/flyers/rf-062.jpg',
    publishedAt: '2026-04-05T11:00:00',
    date: '2026-04-05T11:00:00',
    expiresAt: '2026-05-25T00:00:00',
    author: 'Roberto Sánchez',
    readTime: 9,
  },

  // ─── EDITORIAL adicional ─────────────────────────────────────────────────────

  {
    id: 'ed-006',
    slug: 'editorial-sound-systems-mexico',
    type: 'editorial',
    title: 'El sound system como acto político en México',
    subtitle: 'Por Marco Reyes',
    excerpt: 'En México, armar y mover un sound system no es solo logística: es una declaración sobre quién tiene derecho a ocupar el espacio público y producir experiencias colectivas.',
    bodyPreview: 'La cultura del sound system llegó a México de manera oblicua. No por la ruta directa del reggae jamaicano al grime londinense, sino a través de fragmentos: sistemas de fiesta en el desierto, cumbias tocadas con equipos caseros en Oaxaca, experiencias rave de los 90 importadas por gente que había estado en el Reino Unido.\n\nLo que tardó más en llegar fue el componente político. En el Reino Unido, el sound system siempre fue inseparable de la resistencia: frente a la Criminal Justice Act de 1994, frente al racismo sistémico. En México, esa dimensión tardó en articularse de manera consciente.\n\nHoy, con proyectos como el Jardín Sonoro o las fiestas de El Bajo, empieza a existir un discurso explícito: mover un sistema de varios kilowatts a un parque público, hacer que 300 personas paguen lo que puedan, negarse a programar en venues que cobran $800 por una cerveza. Actos políticos aunque nadie los nombre así.',
    vibe: 5,
    genres: ['techno-raw', 'dub', 'organic-house'],
    tags: ['community', 'free'],
    imageUrl: '/flyers/rf-063.jpg',
    publishedAt: '2026-04-14T08:00:00',
    date: '2026-04-14T08:00:00',
    expiresAt: '2026-07-14T00:00:00',
    author: 'Marco Reyes',
    readTime: 11,
  },

  {
    id: 'ed-007',
    slug: 'editorial-productores-mexicanos-exportacion',
    type: 'editorial',
    title: 'La generación de exportación: productores mexicanos en el mapa global',
    subtitle: 'Por Valeria Mora',
    excerpt: 'De Siete Catorce a N.A.A.F.I., de Debit a Cøsmetic: por primera vez en la historia de la música electrónica, México no es solo consumidor de tendencias globales.',
    bodyPreview: 'Durante décadas, la pregunta que toda persona de la escena mexicana llevaba implícita era la misma: ¿por qué lo bueno siempre viene de afuera? Detroit, Berlín, Londres. Chicago, Bruselas. Los festivales mexicanos llenaban sus carteles con nombres importados porque esos nombres traían certeza de calidad.\n\nEse modelo está roto. No de golpe, pero hay una grieta que se hace más ancha. Siete Catorce tocó en el CTM de Berlín antes de tener una residencia en CDMX. Debit está de gira por Europa mientras en México la descubrimos. N.A.A.F.I. tiene más cobertura en Resident Advisor que en cualquier medio nacional.\n\nLo interesante no es solo que lleguen a esos escenarios, sino que lo hacen siendo explícitamente mexicanos. No hay mimetismo con las estéticas europeas. Siete Catorce habla del Popocatépetl. Debit procesa sonidos de la Ciudad de México. N.A.A.F.I. reivindica el deconstructed club como forma latinoamericana.',
    vibe: 7,
    genres: ['techno-raw', 'deconstructed', 'electronica'],
    tags: ['community'],
    imageUrl: '/flyers/rf-064.jpg',
    publishedAt: '2026-04-10T08:00:00',
    date: '2026-04-10T08:00:00',
    expiresAt: '2026-07-10T00:00:00',
    author: 'Valeria Mora',
    readTime: 13,
    editorial: true,
  },

  {
    id: 'ed-008',
    slug: 'editorial-cumbia-electronica-dignidad',
    type: 'editorial',
    title: 'Cumbia electrónica: el género que nadie sabe cómo llamar',
    subtitle: 'Por Roberto Sánchez',
    excerpt: 'No es cumbia digital ni electrocumbia ni sonidero: existe en el espacio liminal entre la tradición y la pista de baile globalizada, y su falta de nombre es su mayor fortaleza.',
    vibe: 6,
    genres: ['cumbia-electronica', 'latin-electronic', 'cumbia'],
    tags: ['community'],
    imageUrl: '/flyers/rf-065.jpg',
    publishedAt: '2026-04-08T08:00:00',
    date: '2026-04-08T08:00:00',
    expiresAt: '2026-07-08T00:00:00',
    author: 'Roberto Sánchez',
    readTime: 10,
  },

  {
    id: 'ed-009',
    slug: 'editorial-economia-promotores-diy',
    type: 'editorial',
    title: 'La economía imposible del promotor DIY en CDMX',
    subtitle: 'Por Fernanda Lugo',
    excerpt: 'Organizar una fiesta de 300 personas en CDMX puede costarte más de lo que ganas. Una radiografía de la economía invisible que sostiene la escena underground capitalina.',
    bodyPreview: 'Hacer una fiesta en CDMX tiene una lógica perversa que todos conocen pero pocos dicen en voz alta: cuesta más de lo que da. El promotor independiente trabaja a pérdida o en ceros, subsidiado por su trabajo de día.\n\nLos números son brutales. Un venue de capacidad mediana en Roma Norte puede cobrar entre $15,000 y $30,000 de renta base para una noche. A eso súmale el sistema de sonido, los permisos, la producción gráfica, la promoción, y el pago a los artistas. Para cubrir eso necesitas vender 150-200 entradas a $350 antes de que el venue tome su porcentaje de la barra.\n\nY aun así la gente lo hace. La pregunta es por qué.',
    vibe: 4,
    genres: ['electronica', 'techno-raw'],
    tags: ['community'],
    imageUrl: '/flyers/rf-066.jpg',
    publishedAt: '2026-04-06T08:00:00',
    date: '2026-04-06T08:00:00',
    expiresAt: '2026-07-06T00:00:00',
    author: 'Fernanda Lugo',
    readTime: 14,
    editorial: true,
  },

  {
    id: 'ed-010',
    slug: 'shawn-raynaldo-siete-catorce-volcan-ensayo',
    type: 'editorial',
    title: 'Siete Catorce y el volcán: geografía como destino sonoro',
    subtitle: 'Shawn Raynaldo · Substack "Sonidos Nocturnos"',
    excerpt: 'El proyecto de Siete Catorce no es solo música: es una exploración del Popocatépetl como eje narrativo de la identidad sonora mexicana contemporánea.',
    bodyPreview: 'Hay algo que no es accidental en que el proyecto más internacionalmente relevante de la música electrónica mexicana tome su nombre de la alerta volcánica que define la vida en el Valle de México.\n\nSiete Catorce construye música desde esa tensión. Sus tracks no son representaciones del volcán. La referencia es más profunda: es la experiencia de vivir a la sombra de algo que puede matarte en cualquier momento y a lo que sin embargo has aprendido a darle la espalda.\n\nEso es, para Siete Catorce, lo que significa ser mexicano en 2026. Y es también lo que define al techno en su forma más honesta: música hecha en la sombra de sistemas que te pueden destruir.',
    vibe: 9,
    genres: ['techno-raw', 'noise', 'electronica', 'ambient-techno'],
    tags: ['community'],
    imageUrl: '/flyers/rf-067.jpg',
    publishedAt: '2026-04-04T08:00:00',
    date: '2026-04-04T08:00:00',
    expiresAt: '2026-07-04T00:00:00',
    author: 'Shawn Raynaldo',
    readTime: 15,
  },

  {
    id: 'ed-011',
    slug: 'editorial-clubbing-accesibilidad',
    type: 'editorial',
    title: '¿Para quién es el club? Accesibilidad, precio y escena',
    subtitle: 'Por Daniela Ríos',
    excerpt: 'Con entradas que rondan los $500 y venues que no tienen rampa ni baño neutro, la escena underground de CDMX tiene un problema de accesibilidad que nadie quiere nombrar.',
    vibe: 5,
    genres: ['electronica'],
    tags: ['community', 'lgbtq', 'feminist'],
    imageUrl: '/flyers/rf-068.jpg',
    publishedAt: '2026-04-03T08:00:00',
    date: '2026-04-03T08:00:00',
    expiresAt: '2026-07-03T00:00:00',
    author: 'Daniela Ríos',
    readTime: 10,
  },

  // ─── OPINIÓN ────────────────────────────────────────────────────────────────

  {
    id: 'op-001',
    slug: 'opinion-underground-mainstream',
    type: 'opinion',
    title: 'El underground mainstream ya no es underground',
    excerpt: 'Cuando tu fiesta "experimental" viene con influencer en la guest list y algoritmo de Spotify en la curaduría, algo se rompió. No lo estoy celebrando.',
    vibe: 6,
    genres: ['techno-raw', 'deconstructed'],
    tags: ['community'],
    imageUrl: '/flyers/rf-069.jpg',
    publishedAt: '2026-04-17T07:00:00',
    date: '2026-04-17T07:00:00',
    expiresAt: '2026-06-17T00:00:00',
    author: 'Shawn Raynaldo',
    readTime: 5,
    editorial: true,
  },

  {
    id: 'op-002',
    slug: 'opinion-prensa-musical-seria',
    type: 'opinion',
    title: '¿Necesita la escena una prensa musical seria?',
    excerpt: 'Vivimos de reseñas de Instagram que duran 48 horas y ninguna que dure 48 meses. La escena no necesita más cobertura — necesita mejor memoria.',
    vibe: 4,
    genres: ['electronica'],
    tags: ['community'],
    imageUrl: '/flyers/rf-070.jpg',
    publishedAt: '2026-04-15T07:30:00',
    date: '2026-04-15T07:30:00',
    expiresAt: '2026-06-15T00:00:00',
    author: 'Valeria Mora',
    readTime: 4,
    editorial: true,
  },

  {
    id: 'op-003',
    slug: 'opinion-residents-vs-headliners',
    type: 'opinion',
    title: 'Residents locales vs. headliners internacionales',
    excerpt: 'Pagamos $600 por ver a alguien que cobró $8,000 de cachet y $150 por el resident que lleva cinco años construyendo la cultura del venue. Algo está mal en esa ecuación.',
    vibe: 5,
    genres: ['techno-raw', 'industrial'],
    tags: ['community'],
    imageUrl: '/flyers/rf-071.jpg',
    publishedAt: '2026-04-12T07:30:00',
    date: '2026-04-12T07:30:00',
    expiresAt: '2026-06-12T00:00:00',
    author: 'Marco Reyes',
    readTime: 6,
  },

  {
    id: 'op-004',
    slug: 'opinion-gentrificacion-venues',
    type: 'opinion',
    title: 'La gentrificación llegó a los clubs y la estamos dejando pasar',
    excerpt: 'Roma Norte ya no es Roma Norte. Y los venues que antes eran refugios se están convirtiendo en experiencias de lifestyle para gente que no sabe qué es el EBM.',
    vibe: 5,
    genres: ['techno-raw', 'industrial', 'electronica'],
    tags: ['community'],
    imageUrl: '/flyers/rf-072.jpg',
    publishedAt: '2026-04-09T07:30:00',
    date: '2026-04-09T07:30:00',
    expiresAt: '2026-06-09T00:00:00',
    author: 'Fernanda Lugo',
    readTime: 7,
    editorial: true,
  },

  {
    id: 'op-005',
    slug: 'opinion-sobriedadyclub',
    type: 'opinion',
    title: 'Ir de fiesta sober: la escena no sabe qué hacer contigo',
    excerpt: 'Decidí dejar el alcohol hace dos años y seguir yendo a clubes. Lo que aprendí sobre cómo están diseñados estos espacios para que necesites beber es bastante revelador.',
    vibe: 5,
    genres: ['electronica', 'techno-raw'],
    tags: ['community', 'lgbtq'],
    imageUrl: '/flyers/rf-073.jpg',
    publishedAt: '2026-04-06T07:30:00',
    date: '2026-04-06T07:30:00',
    expiresAt: '2026-06-06T00:00:00',
    author: 'Daniela Ríos',
    readTime: 6,
  },

  // ─── PARTNERS (rail) ─────────────────────────────────────────────────────
  // Independent zone — chronological by partnerLastUpdated, no ranking, no vibe filter.

  {
    id: 'pa-naafi',
    slug: 'naafi',
    type: 'partner',
    title: 'N.A.A.F.I.',
    subtitle: 'Sello · CDMX',
    vibe: 7,
    genres: [],
    tags: [],
    imageUrl: '/flyers/rf-074.jpg',
    publishedAt: '2026-04-17T10:00:00',
    partnerKind: 'label',
    partnerUrl: 'https://naafi.net',
    partnerLastUpdated: '2026-04-17T10:00:00',
  },
  {
    id: 'pa-club-japan',
    slug: 'club-japan',
    type: 'partner',
    title: 'Club Japan',
    subtitle: 'Venue · Roma Norte',
    vibe: 8,
    genres: [],
    tags: [],
    imageUrl: '/flyers/rf-075.jpg',
    publishedAt: '2026-04-16T12:00:00',
    partnerKind: 'venue',
    partnerUrl: 'https://instagram.com/japan_cdmx',
    partnerLastUpdated: '2026-04-16T12:00:00',
  },
  {
    id: 'pa-fascinoma',
    slug: 'fascinoma',
    type: 'partner',
    title: 'FASCiNOMA',
    subtitle: 'Promotora · Festival',
    vibe: 6,
    genres: [],
    tags: [],
    imageUrl: '/flyers/rf-076.jpg',
    publishedAt: '2026-04-15T09:00:00',
    partnerKind: 'promoter',
    partnerUrl: 'https://fascinoma.space',
    partnerLastUpdated: '2026-04-15T09:00:00',
  },
  {
    id: 'pa-multiforo-alicia',
    slug: 'multiforo-alicia',
    type: 'partner',
    title: 'Multiforo Alicia',
    subtitle: 'Venue · Roma',
    vibe: 5,
    genres: [],
    tags: [],
    imageUrl: '/flyers/rf-077.jpg',
    publishedAt: '2026-04-13T18:00:00',
    partnerKind: 'venue',
    partnerUrl: 'https://forodealiciatickets.com',
    partnerLastUpdated: '2026-04-13T18:00:00',
  },
  {
    id: 'pa-passline',
    slug: 'passline-promo',
    type: 'partner',
    title: 'Passline · Boletos sin cargos',
    subtitle: 'Promo · Mayo',
    vibe: 5,
    genres: [],
    tags: [],
    imageUrl: '/flyers/rf-078.jpg',
    publishedAt: '2026-04-10T08:00:00',
    partnerKind: 'sponsored',
    partnerUrl: 'https://passline.com',
    partnerLastUpdated: '2026-04-10T08:00:00',
  },
]
