import type { ContentItem } from './types'

export const NOCHE_NEGRA_ITEMS: ContentItem[] = [
  // ─── NOCHE NEGRA — partner catalogue (dev-seed demo) ─────────────────────
  // A mature partner archive: what a promoter's focus cluster looks like
  // months/years in. Every item carries partnerId "pa-noche-negra" (mirrors
  // the prod partner row id) + real metadata researched 2026-08-19: events
  // from RA/press, mixes verified on SC/Mixcloud, reviews of real releases,
  // listicle tracks verified on YouTube. Images live in public/flyers/nn-*.
  // The Sonidos por Venezuela noticia summarizes Revista Marvin's coverage
  // in our own words and links the original — full text deliberately NOT
  // copied (press copyright).

  // — Eventos —

  {
    id: "ev-nn-sonidos-venezuela",
    partnerId: "pa-noche-negra",
    hp: 120,
    hpLastUpdatedAt: "2026-08-18T12:00:00Z",
    slug: "sonidos-por-venezuela-salon-los-angeles",
    type: "evento",
    title: "SONIDOS POR VENEZUELA",
    subtitle: "Baile solidario · Salón Los Ángeles · Vinyl Only",
    excerpt:
      "Baile solidario para recaudar fondos para los damnificados del terremoto de junio en Venezuela. Once actos en el salón más legendario de la ciudad: cumbia, salsa y sonido de bocina grande, todo en vinilo, todo por una causa.",
    vibeMin: 5, vibeMax: 8,
    genres: ["cumbia", "salsa", "cumbia-sonidera", "sonidero"],
    tags: ["benefit", "community", "vinyl-only", "sala-grande"],
    imageUrl: "/flyers/nn-sonidos-flyer.jpg",
    publishedAt: "2026-07-10T12:00:00",
    date: "2026-07-24T19:00:00",
    endDate: "2026-07-25T02:00:00",
    expiresAt: "2026-07-25T06:00:00",
    venue: "Salón Los Ángeles",
    venueCity: "CDMX · Lerdo 206, Col. Guerrero",
    artists: [
      "Señora Cumbiaamba",
      "Yesú Yembé",
      "Digital Charanga",
      "Sonidera Mx",
      "Sonido Fuegorama",
      "Sonido Sabotaje",
      "DJ Chiakka",
      "Las Veredas",
      "Sonidera Nacional",
      "Grow Disc",
      "PedraSound",
    ],
    price: "Donativo vía Passline",
    ticketUrl: "https://www.passline.com/eventos/sonidos-por-venezuela-baile-solidario",
    editorial: true,
    links: [
      { label: "Cobertura en Revista Marvin", url: "https://marvin.com.mx/sonidos-por-venezuela-noche-negra/" },
    ],
  },

  {
    id: "ev-nn-tonal-oct25",
    partnerId: "pa-noche-negra",
    slug: "noche-negra-tonal-oct-2025",
    type: "evento",
    title: "NOCHE NEGRA EN TONAL",
    subtitle: "Jueves de vinil · Roma Norte",
    excerpt:
      "La fiesta itinerante aterriza en Tonal: una noche de jueves con los All Stars del colectivo detrás de las tornamesas. Salsa, cumbia y rarezas tropicales en 45s, de nueve a tres.",
    vibeMin: 5, vibeMax: 7,
    genres: ["salsa", "cumbia", "latin-jazz"],
    tags: ["club-night", "vinyl-only"],
    imageUrl: "/flyers/nn-tonal-oct25.jpg",
    publishedAt: "2025-09-28T12:00:00",
    date: "2025-10-16T21:00:00",
    endDate: "2025-10-17T03:00:00",
    expiresAt: "2025-10-17T06:00:00",
    venue: "Tonal",
    venueCity: "CDMX · Av. Álvaro Obregón 160, Roma Norte",
    artists: ["Nochenegra All Stars"],
    price: "$250",
    ticketUrl: "https://ra.co/events/2283562",
  },

  {
    id: "ev-nn-agenda-tonal",
    partnerId: "pa-noche-negra",
    slug: "agenda-tonal-nochenegra-abril-2025",
    type: "evento",
    title: "AGENDA TONAL",
    subtitle: "Nochenegra All Stars + invitados",
    excerpt:
      "El ciclo Agenda Tonal recibe al colectivo con una alineación mixta: selectores de casa y invitados que cruzan el bolero, la cumbia y el groove. Miércoles de escucha fina y baile suelto.",
    vibeMin: 4, vibeMax: 6,
    genres: ["cumbia", "salsa", "jazz-latino"],
    tags: ["club-night", "vinyl-only", "b2b"],
    imageUrl: "/flyers/nn-ig-03.jpg",
    publishedAt: "2025-03-20T12:00:00",
    date: "2025-04-02T21:00:00",
    endDate: "2025-04-03T02:00:00",
    expiresAt: "2025-04-03T06:00:00",
    venue: "Tonal",
    venueCity: "CDMX · Av. Álvaro Obregón 160, Roma Norte",
    artists: ["Omar Velasco", "Beyou Thomass", "Jackson b2b Bubu", "Nochenegra All Stars"],
    price: "$200",
    ticketUrl: "https://ra.co/events/2139740",
  },

  {
    id: "ev-nn-bienvenido-2026",
    partnerId: "pa-noche-negra",
    slug: "bienvenido-2026-salon-solin",
    type: "evento",
    title: "BIENVENIDO 2026",
    subtitle: "Año nuevo · nueve años de buenas fiestas",
    excerpt:
      "El colectivo despide el año marcando nueve de fiestas de cumbia y salsa de primer nivel. Salón Solín, doce horas de vinil, uvas a medianoche y bocina grande hasta el amanecer.",
    vibeMin: 6, vibeMax: 8,
    genres: ["cumbia", "salsa", "sonidero"],
    tags: ["club-night", "vinyl-only", "anl", "sala-grande"],
    imageUrl: "/flyers/nn-nye-2026.jpg",
    publishedAt: "2025-12-10T12:00:00",
    date: "2025-12-31T21:00:00",
    endDate: "2026-01-01T06:00:00",
    expiresAt: "2026-01-01T12:00:00",
    venue: "Salón Solín",
    venueCity: "CDMX",
    artists: ["Nochenegra All Stars"],
    price: "$450 · Early bird en Passline",
    ticketUrl: "https://ra.co/events/2333655",
  },

  {
    id: "ev-nn-baile-del-ano",
    partnerId: "pa-noche-negra",
    slug: "el-baile-del-ano-salon-los-angeles-2024",
    type: "evento",
    title: "EL BAILE DEL AÑO",
    subtitle: "Nochenegra + Grow Disc · cumbre sonidera",
    excerpt:
      "El cruce del colectivo con la cultura sonidera de la ciudad: Alberto Pedraza en vivo, Los Daddy's con Chucho Ponce, MemoMix Tepito 'El Jefe del Vinil' y las Musas Sonideras compartiendo cabina en el Salón Los Ángeles.",
    vibeMin: 6, vibeMax: 8,
    genres: ["cumbia-sonidera", "sonidero", "cumbia"],
    tags: ["sala-grande", "vinyl-only", "community", "soundsystem"],
    imageUrl: "/flyers/nn-baile-del-ano.jpg",
    publishedAt: "2024-10-20T12:00:00",
    date: "2024-11-09T19:00:00",
    endDate: "2024-11-10T02:00:00",
    expiresAt: "2024-11-10T06:00:00",
    venue: "Salón Los Ángeles",
    venueCity: "CDMX · Lerdo 206, Col. Guerrero",
    artists: [
      "Alberto Pedraza",
      "Los Daddy's",
      "MemoMix Tepito",
      "Sonido Gipsy",
      "Musas Sonideras",
      "Sonido Confirmación",
      "Noche Negra All Stars",
    ],
    price: "$300",
    links: [
      { label: "Agenda Indie Rocks!", url: "https://www.indierocks.mx/agenda/nochenegra-y-grow-disc-presentan-el-baile-del-ano/" },
    ],
  },

  {
    id: "ev-nn-club-coco",
    partnerId: "pa-noche-negra",
    slug: "club-coco-cdmx-nochenegra-2024",
    type: "evento",
    title: "CLUB COCO EN CDMX",
    subtitle: "Coco María x Nochenegra · Festival Rayón",
    excerpt:
      "La curadora de Club Coco trae su maleta de discos a la ciudad, presentada por el colectivo junto al Festival Rayón. Cumbia, jazz latino y pop internacional de todas las décadas — la fiesta que su show de radio promete cada lunes.",
    vibeMin: 4, vibeMax: 7,
    genres: ["cumbia", "nu-cumbia", "jazz-latino", "latin-jazz"],
    tags: ["club-night", "vinyl-only", "showcase"],
    imageUrl: "/flyers/nn-ig-01.jpg",
    publishedAt: "2024-11-01T12:00:00",
    date: "2024-11-23T21:00:00",
    endDate: "2024-11-24T03:00:00",
    expiresAt: "2024-11-24T06:00:00",
    venue: "Festival Rayón",
    venueCity: "CDMX",
    artists: ["Coco María", "Nochenegra All Stars"],
    price: "+21 · Passline",
    ticketUrl: "https://www.passline.com/eventos/club-coco-en-cdmx-x-nochenegra-festival-rayon",
  },

  // — Mixes (selectores ligados al colectivo; sesiones reales verificadas) —

  {
    id: "mx-nn-carlos-rene",
    partnerId: "pa-noche-negra",
    hp: 70,
    hpLastUpdatedAt: "2026-08-18T12:00:00Z",
    slug: "carlos-rene-salsa-en-mexico-nts",
    type: "mix",
    title: "Salsa en México",
    subtitle: "Carlos René · NTS desde CDMX",
    excerpt:
      "Cómo la guaracha cubana, el son montuno y la rumba cruzaron el Golfo por Veracruz y Yucatán — y cómo las Sonoras mexicanas de los cincuenta a los setenta forjaron su propio tumbao. Metales, congas y voces con sabor, contado en discos por el cofundador de Casa Calypso.",
    vibeMin: 4, vibeMax: 6,
    genres: ["salsa", "latin-jazz"],
    tags: ["radio", "vinyl-only"],
    imageUrl: "/flyers/nn-mix-carlos-rene.jpg",
    publishedAt: "2025-09-18T12:00:00",
    date: "2025-09-18T12:00:00",
    duration: "59:59",
    mixUrl: "https://www.mixcloud.com/NTSRadio/carlos-ren%C3%A9-salsa-en-m%C3%A9xico-18th-september-2025/",
    embeds: [
      { platform: "mixcloud", url: "https://www.mixcloud.com/NTSRadio/carlos-ren%C3%A9-salsa-en-m%C3%A9xico-18th-september-2025/" },
    ],
    tracklist: [
      { artist: "Los Hermanos Medina", title: "El Reloj De Pastora" },
      { artist: "Lobo Y Melón", title: "Margarito" },
      { artist: "Lolita Peraza Y La Sonora De Baldomero", title: "Soy Sabrosura" },
    ],
    mixFormat: "Radio Show",
    recordedIn: "CDMX",
    mixStatus: "disponible",
    author: "Carlos René",
    artists: ["Carlos René"],
    links: [
      { label: "Episodio en NTS", url: "https://www.nts.live/shows/carlos-rene/episodes/carlos-rene-18th-september-2025" },
    ],
  },

  {
    id: "mx-nn-coco-maria",
    partnerId: "pa-noche-negra",
    slug: "coco-maria-le-mellotron",
    type: "mix",
    title: "Coco María en Le Mellotron",
    subtitle: "Soul · Cumbia · Salsa · Jazz",
    excerpt:
      "Sesión de estudio para la radio parisina: la maleta viajera de la curadora de Club Coco en modo cálido — soul, cumbia, salsa y jazz que suenan a verano aunque afuera llueva.",
    vibeMin: 3, vibeMax: 6,
    genres: ["cumbia", "salsa", "jazz-latino"],
    tags: ["radio", "vinyl-only"],
    imageUrl: "/flyers/nn-mix-coco-maria.jpg",
    publishedAt: "2019-02-11T12:00:00",
    date: "2019-02-11T12:00:00",
    duration: "53:10",
    mixUrl: "https://soundcloud.com/lemellotron/coco-maria-dj-set",
    embeds: [
      { platform: "soundcloud", url: "https://soundcloud.com/lemellotron/coco-maria-dj-set" },
    ],
    mixFormat: "DJ Set",
    recordedIn: "París",
    mixStatus: "archivo",
    author: "Coco María",
    artists: ["Coco María"],
  },

  {
    id: "mx-nn-sonido-martines",
    partnerId: "pa-noche-negra",
    slug: "sonido-martines-el-humo-mundial",
    type: "mix",
    title: "El Humo Mundial",
    subtitle: "Sonido Martines · NTS",
    excerpt:
      "Una hora de excavación por el sur global: cumbia selvática, carimbó, buri y jazz latino desde la colección del cazador de discos radicado en Bolivia. Radio de raíz con oído de club.",
    vibeMin: 3, vibeMax: 6,
    genres: ["cumbia", "folclore-latinoamericano", "latin-jazz"],
    tags: ["radio", "vinyl-only"],
    imageUrl: "/flyers/nn-mix-martines.jpg",
    publishedAt: "2022-06-08T12:00:00",
    date: "2022-06-08T12:00:00",
    duration: "1:00:00",
    mixUrl: "https://soundcloud.com/sonidomartines/el-humo-mundial-con-sonido-martines-8-junio-nts-radio",
    embeds: [
      { platform: "soundcloud", url: "https://soundcloud.com/sonidomartines/el-humo-mundial-con-sonido-martines-8-junio-nts-radio" },
    ],
    tracklist: [
      { artist: "Jichushka", title: "Malafama" },
      { artist: "Banda Buri Cabure", title: "El Carbonero" },
      { artist: "Banda Sapo Pinto, Los Del Paitití", title: "Sinha Pureza" },
      { artist: "Jhuliano", title: "Buscando El Camino" },
    ],
    mixFormat: "Radio Show",
    mixStatus: "archivo",
    author: "Sonido Martines",
    artists: ["Sonido Martines"],
    links: [
      { label: "Episodio en NTS", url: "https://www.nts.live/shows/sonido-martines/episodes/sonido-martines-8th-june-2022" },
    ],
  },

  {
    id: "mx-nn-sonido-confirmacion",
    partnerId: "pa-noche-negra",
    slug: "sonido-confirmacion-introduccion-sonidera",
    type: "mix",
    title: "Introducción al sonido sonidero",
    subtitle: "Sonido Confirmación para Resident Advisor",
    excerpt:
      "Danny Alvarado condensa en cuarenta minutos lo que suena en las bocinas de las fiestas sonideras de la ciudad: cumbia tropical, saludos y bajo grande. El mix que acompañó el reportaje de RA sobre los soundsystems móviles de CDMX.",
    vibeMin: 4, vibeMax: 7,
    genres: ["cumbia-sonidera", "sonidero", "cumbia"],
    tags: ["soundsystem", "community"],
    imageUrl: "/flyers/nn-mix-confirmacion.jpg",
    publishedAt: "2018-04-23T12:00:00",
    date: "2018-04-23T12:00:00",
    duration: "40:19",
    mixUrl: "https://soundcloud.com/resident-advisor/sonido-confirmacion-sonidero-mix",
    embeds: [
      { platform: "soundcloud", url: "https://soundcloud.com/resident-advisor/sonido-confirmacion-sonidero-mix" },
    ],
    mixFormat: "DJ Set",
    recordedIn: "CDMX",
    mixStatus: "archivo",
    author: "Sonido Confirmación",
    artists: ["Sonido Confirmación"],
    links: [
      { label: "Reportaje de RA sobre sonideros", url: "https://ra.co/features/3203" },
    ],
  },

  {
    id: "mx-nn-tropicaza",
    partnerId: "pa-noche-negra",
    slug: "tropicaza-boiler-room-cdmx",
    type: "mix",
    title: "Boiler Room CDMX: Vinyl Only",
    subtitle: "Tropicaza · Foro Normandie",
    excerpt:
      "La primera transmisión 100% en vinilo de Boiler Room en América Latina, desde el Foro Normandie: Tropicaza presumiendo su colección de todo lo tropical, una hora de puro disco girando.",
    vibeMin: 5, vibeMax: 7,
    genres: ["cumbia", "tropical-bass", "salsa"],
    tags: ["live", "vinyl-only", "dancefloor"],
    imageUrl: "/flyers/nn-mix-tropicaza.jpg",
    publishedAt: "2017-06-13T12:00:00",
    date: "2017-05-21T12:00:00",
    duration: "59:16",
    mixUrl: "https://soundcloud.com/platform/tropicaza-boiler-room-mexico-city-dj-set",
    embeds: [
      { platform: "soundcloud", url: "https://soundcloud.com/platform/tropicaza-boiler-room-mexico-city-dj-set" },
    ],
    mixFormat: "Live",
    recordedIn: "Foro Normandie, CDMX",
    mixStatus: "archivo",
    author: "Tropicaza",
    artists: ["Tropicaza"],
  },

  // — Noticias —

  {
    id: "no-nn-sonidos-venezuela",
    partnerId: "pa-noche-negra",
    hp: 90,
    hpLastUpdatedAt: "2026-08-18T12:00:00Z",
    slug: "sonidos-por-venezuela-recaudacion-salon-los-angeles",
    type: "noticia",
    title: "El salón bailó por Venezuela",
    subtitle: "Baile solidario reúne fondos para los damnificados del terremoto",
    excerpt:
      "Once actos, un salón histórico y una causa: la noche del 24 de julio, el baile solidario convocado por el colectivo llenó el Salón Los Ángeles para recaudar ayuda destinada a los damnificados de los sismos de junio en Venezuela.",
    bodyPreview:
      "La noche del viernes 24 de julio, el Salón Los Ángeles — Lerdo 206, Colonia Guerrero, el salón de baile más legendario de la ciudad — abrió sus puertas desde las siete para una causa urgente: recaudar fondos de ayuda para los damnificados de los terremotos que sacudieron Venezuela el 24 de junio.\n\nBajo el nombre de Sonidos por Venezuela, el cartel reunió once actos de la escena tropical chilanga: Señora Cumbiaamba, Yesú Yembé, Digital Charanga, Sonidera Mx, Sonido Fuegorama, Sonido Sabotaje, DJ Chiakka, Las Veredas, Sonidera Nacional, Grow Disc y PedraSound. La recaudación corrió por venta de boletos vía Passline, y el colectivo organizador — fundado por migrantes venezolanos radicados en CDMX — puso la fiesta al servicio de su tierra: un baile solidario en toda regla, de esos que la Guerrero sabe recibir desde hace un siglo.\n\nLos sismos del 24 de junio — una premonición de 7.2 cerca de San Felipe y el evento principal de 7.5 frente a Catia La Mar — dejaron miles de víctimas y a comunidades enteras sin techo. La respuesta de la diáspora venezolana en México ha tomado muchas formas; pocas tan bailables como esta.\n\nLa cobertura completa del evento es de Revista Marvin (nota de Oscar G. Hernández) — enlace abajo.",
    vibeMin: 5, vibeMax: 7,
    genres: ["cumbia", "salsa", "sonidero"],
    tags: ["benefit", "community", "sala-grande"],
    imageUrl: "/flyers/nn-sonidos-venezuela.jpg",
    publishedAt: "2026-07-25T10:00:00",
    author: "Redacción Gradiente",
    readTime: 3,
    editorial: true,
    links: [
      { label: "Nota completa en Revista Marvin", url: "https://marvin.com.mx/sonidos-por-venezuela-noche-negra/" },
      { label: "Contexto: sismos de junio (Wikipedia)", url: "https://es.wikipedia.org/wiki/Terremotos_de_Venezuela_de_2026" },
    ],
  },

  {
    id: "no-nn-sxsw",
    partnerId: "pa-noche-negra",
    slug: "nochenegra-sxsw-2024-austin",
    type: "noticia",
    title: "La bandera negra ondea en Austin",
    subtitle: "El colectivo llevó su fiesta de vinil a SXSW 2024",
    excerpt:
      "El showcase compartido con Trucha Soul en La Factoria puso la fiesta chilanga de vinil frente al público de South by Southwest: Alejaina, La Gallo 3:20, Los Cogelones y DJ Nyack completaron una noche de ritmos latinoamericanos en Austin.",
    bodyPreview:
      "Nacida en 2017 como fiesta mensual de puro vinilo para celebrar los ritmos de América Latina y el Caribe, la fiesta itinerante cruzó la frontera en marzo de 2024: el showcase junto a Trucha Soul en La Factoria (16 de marzo) formó parte de la programación oficial de SXSW, con Alejaina, La Gallo 3:20, Los Cogelones y DJ Nyack en el cartel.\n\nPara un proyecto que empezó en El Babalú del Salón Ríos y que llegó a juntar cuatro mil personas en su segundo aniversario en el Jardín Juárez, Austin fue menos un salto que una confirmación: la fiesta viaja bien cuando la maleta va llena de discos.",
    vibeMin: 4, vibeMax: 6,
    genres: ["cumbia", "salsa", "world-bass"],
    tags: ["showcase", "vinyl-only", "community"],
    imageUrl: "/flyers/nn-bandera.jpg",
    publishedAt: "2024-03-18T10:00:00",
    author: "Redacción Gradiente",
    readTime: 2,
    links: [
      { label: "Ficha del showcase en SXSW", url: "https://schedule.sxsw.com/2024/artists/2197965" },
    ],
  },

  {
    id: "no-nn-siete-anos",
    partnerId: "pa-noche-negra",
    slug: "nochenegra-siete-anos-buenas-fiestas",
    type: "noticia",
    title: "Siete años de buenas fiestas",
    subtitle: "El colectivo celebra aniversario en una noche llena de estrellas",
    excerpt:
      "De una fiesta privada para fondear un proyecto de cerámica a una institución itinerante de la noche tropical chilanga: el colectivo fundado por Pocz y Mariana Maduro cumple siete años de vinil, migración y baile.",
    bodyPreview:
      "La historia es conocida en la escena pero merece contarse otra vez: en 2015, dos migrantes venezolanos se conocieron en México. La primera fiesta — 'La fiesta negra', privada, tres DJs y una sola regla: música negra — nació para apoyar el Kickstarter de cerámica de Mariana. Para 2017 la fiesta ya tenía nombre, casa en El Babalú del Salón Ríos y una convicción: solo vinilo, solo buenas fiestas.\n\nSiete años después, el aniversario se celebró como se debe: bajo las estrellas, con la bandera negra colgada sobre la cabina y la pista llena. En palabras de Pocz para Indie Rocks!, los discos son piezas de historia y de cultura — y cada fiesta del colectivo es una clase de esa historia que se baila.",
    vibeMin: 4, vibeMax: 7,
    genres: ["salsa", "cumbia", "latin-jazz"],
    tags: ["community", "vinyl-only"],
    imageUrl: "/flyers/nn-ig-02.jpg",
    publishedAt: "2024-06-10T10:00:00",
    author: "Redacción Gradiente",
    readTime: 2,
    links: [
      { label: "Entrevista con los fundadores (Indie Rocks!)", url: "https://www.indierocks.mx/musica/entrevistas/entrevista-con-nochenegra/" },
    ],
  },

  // — Reviews —

  {
    id: "rv-nn-club-coco",
    partnerId: "pa-noche-negra",
    slug: "review-club-coco-bongo-joe",
    type: "review",
    title: "VA — Club Coco",
    subtitle: "Les Disques Bongo Joe · 2021",
    excerpt:
      "La primera compilación de Coco María suena exactamente a lo que promete su radio: una fiesta secuenciada con oído de coleccionista, de la cumbia del asilo de Frente Cumbiero al bolero eléctrico de Malphino. Once cortes que arman una noche entera.",
    bodyPreview:
      "Curada por la selectora mexicana radicada en Ámsterdam, Club Coco (Bongo Joe, mayo 2021) creció de la comunidad alrededor de su show de radio y se nota: no es un sampler de sello, es un set. Nico Mauskovic abre, La Perla pone la percusión bogotana, Meridian Brothers y Grupo Renacimiento detonan su 'Bomba Atómica', y la propia Coco María se estrena como productora con 'Me Veo Volar'.\n\nLa secuencia es el argumento: tropical sin postal, cosmopolita sin frialdad. UK Vibe le dio cinco estrellas y llamó a su curadora una selectora genial; nosotros solo confirmamos que funciona igual de bien en la bocina de la sala que en la del salón.",
    vibeMin: 3, vibeMax: 6,
    genres: ["nu-cumbia", "cumbia", "latin-electronic"],
    tags: ["vinyl-only"],
    imageUrl: "/flyers/nn-club-coco-2021.jpg",
    publishedAt: "2026-05-14T10:00:00",
    author: "Sofía Quintero",
    readTime: 5,
    format: "vinyl",
    subjectKind: "record",
    year: 2021,
    country: "Suiza",
    artists: ["Coco María", "Frente Cumbiero", "Meridian Brothers", "La Perla", "Malphino"],
    links: [
      { label: "Escuchar en Bandcamp", url: "https://lesdisquesbongojoe.bandcamp.com/album/club-coco" },
    ],
  },

  {
    id: "rv-nn-club-coco-ahora",
    partnerId: "pa-noche-negra",
    hp: 60,
    hpLastUpdatedAt: "2026-08-18T12:00:00Z",
    slug: "review-club-coco-ahora",
    type: "review",
    title: "VA — Club Coco ¡AHORA!",
    subtitle: "The Latin Sound of Now · Bongo Joe · 2023",
    excerpt:
      "La segunda entrega de Club Coco cambia el crate por el laboratorio: catorce cortes (trece inéditos) de la comunidad pan-latina post-digital. La cumbia sintética oscura de Lola's Dice y el sufismo bailable de Dip In The Dub marcan el nivel.",
    bodyPreview:
      "Si el primer volumen documentaba una fiesta, ¡AHORA! documenta una escena en tiempo presente: artistas que toman la energía y las texturas de la música latina clásica y las convierten en canciones para una generación nueva. Los Pirañas abren el fuego colombiano, Acid Coco sonríe con dientes, Chúpame El Dedo se declara 'Metalero' y Ronald Snijders aporta la elegancia surinamesa.\n\nOtra vez cinco estrellas de UK Vibe — 'reverencia al pasado a toda máquina hacia el futuro' — y otra vez la sensación de que Coco María no compila discos: compila pistas de baile posibles.",
    vibeMin: 4, vibeMax: 7,
    genres: ["nu-cumbia", "latin-electronic", "cumbia-experimental"],
    tags: ["vinyl-only"],
    imageUrl: "/flyers/nn-club-coco-ahora.jpg",
    publishedAt: "2026-06-02T10:00:00",
    author: "Sofía Quintero",
    readTime: 5,
    format: "vinyl",
    subjectKind: "record",
    year: 2023,
    country: "Suiza",
    artists: ["Coco María", "Los Pirañas", "Lola's Dice", "Acid Coco", "Candeleros"],
    links: [
      { label: "Escuchar en Bandcamp", url: "https://lesdisquesbongojoe.bandcamp.com/album/coco-mar-a-presents-club-coco-ahora-the-latin-sound-of-now" },
    ],
  },

  {
    id: "rv-nn-club-coco-nd",
    partnerId: "pa-noche-negra",
    slug: "review-club-coco-new-dimensions",
    type: "review",
    title: "VA — Club Coco: New Dimensions in Latin Music",
    subtitle: "Club Coco (sello propio) · 2025",
    excerpt:
      "Para el tercer volumen, Coco María ya no le pide permiso a nadie: New Dimensions inaugura su propio sello. Cumbias digitales contra vamps vintage y sintetizadores napolitanos, de Bogotá a Nápoles pasando por Lima, Ámsterdam y Nueva York.",
    bodyPreview:
      "El dato importa: tras dos volúmenes en Bongo Joe, este tercero (septiembre 2025, catálogo CC001) es la primera referencia del sello Club Coco. La curaduría se estira sin romperse: Raz Olsher abre con Luzmira Zerpa en 'Infinite Blue', La China de la Gasolina le dedica una cumbia a 'Ricky Ricardo', Whodamanny trae la fiesta napolitana y Pinchado & Tribilin Sound cierran el ritual limeño.\n\nEs el volumen más suelto de los tres — menos tesis, más atmósfera — y quizás por eso el que mejor retrata lo que es una noche de la curadora: una alegría relajada y de corazón abierto en la que simplemente entras y te quedas.",
    vibeMin: 3, vibeMax: 6,
    genres: ["nu-cumbia", "cumbia-digital", "latin-electronica"],
    tags: ["vinyl-only"],
    imageUrl: "/flyers/nn-club-coco-nd.jpg",
    publishedAt: "2025-10-08T10:00:00",
    author: "Emiliano Vega",
    readTime: 4,
    format: "vinyl",
    subjectKind: "record",
    year: 2025,
    country: "Países Bajos",
    artists: ["Coco María", "Raz Olsher", "La China de la Gasolina", "Whodamanny"],
    links: [
      { label: "Escuchar en Bandcamp", url: "https://clubcoco.bandcamp.com/album/club-coco-new-dimensions-in-latin-music" },
    ],
  },

  {
    id: "rv-nn-elia-elizabeth",
    partnerId: "pa-noche-negra",
    slug: "review-la-onda-de-elia-y-elizabeth",
    type: "review",
    title: "Elia y Elizabeth — La Onda de Elia y Elizabeth",
    subtitle: "Vampisoul · reedición curada por Tropicaza",
    excerpt:
      "El dúo de hermanas colombianas que en 1972-73 inventó, sin proponérselo, un pop tropical-pastoral irrepetible. La reedición de Vampisoul — con notas de Carlos Icaza, alias Tropicaza — es la puerta de entrada definitiva.",
    bodyPreview:
      "Dieciséis cortes tomados de los dos LPs originales del dúo: soft-pop con un toque de funk tropical-pastoral, canción de autor endulzada por el perfume sutil del Caribe y una psicodelia amable. Así lo describen las notas del librito, firmadas por Carlos Icaza — el investigador y selector chilango conocido en cabina como Tropicaza, colaborador de años del sello madrileño.\n\nLa reedición hace lo que las buenas reediciones hacen: no rescata una curiosidad, restituye un mundo. Las fotos del archivo personal de Elia Fleta completan el paquete. Para la pista funciona mejor de lo que su dulzura sugiere — pregúntenle a cualquiera que haya escuchado 'Alegría' sonar en un salón a la una de la mañana.",
    vibeMin: 2, vibeMax: 5,
    genres: ["folclore-latinoamericano", "latin-jazz", "cumbia"],
    tags: ["vinyl-only"],
    imageUrl: "/flyers/nn-elia-elizabeth.jpg",
    publishedAt: "2026-03-12T10:00:00",
    author: "Emiliano Vega",
    readTime: 4,
    format: "vinyl",
    subjectKind: "record",
    year: 2019,
    country: "Colombia",
    artists: ["Elia y Elizabeth", "Tropicaza"],
    links: [
      { label: "Escuchar en Bandcamp", url: "https://vampisoul.bandcamp.com/album/la-onda-de-elia-y-elizabeth" },
    ],
  },

  // — Opiniones —

  {
    id: "op-nn-mas-salsa",
    partnerId: "pa-noche-negra",
    slug: "por-que-no-hay-mas-salsa-noche-chilanga",
    type: "opinion",
    title: "¿Por qué no hay más salsa en la noche chilanga?",
    subtitle: "Una asistente asidua se lo pregunta en serio",
    excerpt:
      "Tenemos los salones, tenemos las orquestas, tenemos cien años de tradición tropical — y sin embargo la agenda de la ciudad se llena de kicks a 140. No es guerra de géneros: es una pregunta de memoria.",
    bodyPreview:
      "Cada vez que salgo de una fiesta tropical con la garganta rasposa de tanto corear, me pregunto lo mismo: ¿por qué esto pasa una vez al mes y no todos los fines? La ciudad tiene la infraestructura — los salones llevan un siglo de pie — y tiene al público: basta ver la fila en Lerdo 206 media hora antes de que abran.\n\nNo pido menos techno. Pido más pista para el tumbao: más fiestas que pongan a Lobo y Melón junto a la cumbia rebajada, más selectores que sepan que una charanga bien puesta llena igual que cualquier drop. Los colectivos que lo están haciendo — con vinilo, con cariño, con bandera — demuestran que el público existe. Falta que el resto de la noche se dé cuenta.",
    vibeMin: 4, vibeMax: 6,
    genres: ["salsa", "cumbia"],
    tags: ["community", "dancefloor"],
    imageUrl: "/flyers/nn-baile-vidas-2021.jpg",
    publishedAt: "2026-06-18T10:00:00",
    author: "Lucía Barragán",
    readTime: 4,
  },

  {
    id: "op-nn-salones",
    partnerId: "pa-noche-negra",
    hp: 55,
    hpLastUpdatedAt: "2026-08-18T12:00:00Z",
    slug: "elogio-del-salon-mexicano",
    type: "opinion",
    title: "Elogio del salón",
    subtitle: "Por qué amo bailar en los salones mexicanos",
    excerpt:
      "En el club se va a ver y ser visto; en el salón se va a bailar. Sobre pistas de duela, meseros con charola, luz de neón vieja y la democracia perfecta de una pieza bien tocada.",
    bodyPreview:
      "El Salón Los Ángeles abrió en 1937 y su lema no ha cambiado: quien no conoce el salón, no conoce la ciudad. Ahí no importa tu outfit ni tu lista de invitados; importa si sabes llevar el paso, y si no sabes, alguien te enseña. Esa es la diferencia fundamental con el club: el salón es una institución pedagógica.\n\nLas mesas alrededor de la pista no son decoración — son la estructura social del baile: se llega en grupo, se descansa en grupo, se sale a la duela en parejas que rotan. Cuando un colectivo joven mete su fiesta de vinil a un salón de estos, no está haciendo algo retro: está devolviendo la música al mueble que la ciudad construyó para ella. Larga vida a la duela.",
    vibeMin: 3, vibeMax: 5,
    genres: ["salsa", "cumbia", "sonidero"],
    tags: ["sala-grande", "community"],
    imageUrl: "/flyers/nn-aniversario-2022.jpg",
    publishedAt: "2026-08-06T10:00:00",
    author: "Emiliano Vega",
    readTime: 5,
  },

  {
    id: "op-nn-vinyl-only",
    partnerId: "pa-noche-negra",
    slug: "vinyl-only-fiesta-como-memoria",
    type: "opinion",
    title: "Vinyl only: la fiesta como acto de memoria",
    subtitle: "Lo que cambia cuando la noche gira a 45 revoluciones",
    excerpt:
      "Un USB no se puede dedicar. Sobre lo que significa que una fiesta entera dependa de dos maletas de discos: el riesgo, el ritual y la memoria material de la música que nos hizo.",
    bodyPreview:
      "Los fundadores del colectivo lo han dicho en entrevistas: los discos son piezas de historia y de cultura. Suena a frase hecha hasta que ves la cabina en vivo — la aguja que se posa, el selector que escucha el final de una pieza con el siguiente 45 ya en la mano, el error posible en cada mezcla. El vinilo obliga a un tipo de atención que el sync mató.\n\nY hay algo más: la fiesta de vinil es un archivo ambulante. Cada 45 de charanga que suena en un salón de la Guerrero es un documento que sobrevivió a mudanzas, aduanas y décadas de olvido para volver a hacer exactamente su trabajo original: poner a bailar a un cuarto lleno de gente. Eso no es nostalgia. Es continuidad.",
    vibeMin: 3, vibeMax: 5,
    genres: ["salsa", "cumbia", "latin-jazz"],
    tags: ["vinyl-only", "ritual"],
    imageUrl: "/flyers/nn-ig-04.jpg",
    publishedAt: "2026-05-20T10:00:00",
    author: "Lucía Barragán",
    readTime: 4,
  },

  // — Listicles —

  {
    id: "li-nn-subgeneros-salsa",
    partnerId: "pa-noche-negra",
    hp: 95,
    hpLastUpdatedAt: "2026-08-18T12:00:00Z",
    slug: "cinco-subgeneros-raros-salsa",
    type: "listicle",
    title: "5 subgéneros raros (pero reales) de la salsa",
    subtitle: "Y el track esencial de cada uno",
    excerpt:
      "La salsa no es un género: es un archipiélago. Cinco islas poco visitadas — de la pachanga al salsa choke — con una pieza esencial para desembarcar en cada una.",
    vibeMin: 4, vibeMax: 7,
    genres: ["salsa", "latin-jazz"],
    tags: ["dancefloor"],
    imageUrl: "/flyers/nn-li-subgeneros.jpg",
    publishedAt: "2026-07-02T11:00:00",
    date: "2026-07-02T11:00:00",
    author: "Redacción Gradiente",
    editorial: true,
    artists: ["Joe Quijano", "Cali Flow Latino", "NG La Banda", "Willie Colón", "Rubén Blades", "Orquesta Broadway"],
    articleBody: [
      {
        kind: "lede",
        text: "Decir 'salsa' es como decir 'electrónica': una palabra que aplana medio siglo de mutaciones. Aquí van cinco ramas verificablemente reales del árbol — cada una con su historia y con el disco que la explica mejor que cualquier párrafo.",
      },
      { kind: "divider" },
      {
        kind: "track",
        rank: 5,
        artist: "Joe Quijano y Su Orquesta",
        title: "La Pachanga Se Baila Así",
        year: 1962,
        imageUrl: "https://i.ytimg.com/vi/V7HA17gc6tQ/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=V7HA17gc6tQ" }],
        commentary:
          "PACHANGA. Inventada por el cubano Eduardo Davidson en 1959, la fiebre cruzó a Nueva York en meses. Este sencillo de Columbia — con Charlie Palmieri al piano — literalmente instruye a la pista sobre cómo se baila.",
      },
      {
        kind: "track",
        rank: 4,
        artist: "Orquesta Broadway",
        title: "Isla del Encanto",
        year: 1978,
        imageUrl: "https://i.ytimg.com/vi/-91JHM3sD9o/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=-91JHM3sD9o" }],
        commentary:
          "CHARANGA. Flautas y violines heredados de la contradanza cubana del XIX, en plena era Fania. La institución neoyorquina demostró que una charanga pega tan duro como cualquier conjunto de metales — esta oda a Puerto Rico sigue siendo su pieza más querida.",
      },
      {
        kind: "track",
        rank: 3,
        artist: "Willie Colón & Rubén Blades",
        title: "Plástico",
        year: 1978,
        imageUrl: "https://i.ytimg.com/vi/ssYs12sLAp4/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=ssYs12sLAp4" }],
        commentary:
          "SALSA CONSCIENTE. El ala político-poética del género tiene hasta bibliografía académica. Abre Siembra — el disco de salsa más vendido de la historia — con un manifiesto antimaterialista que todavía incomoda en las bodas.",
      },
      {
        kind: "track",
        rank: 2,
        artist: "NG La Banda",
        title: "La Bruja",
        year: 1994,
        imageUrl: "https://i.ytimg.com/vi/p-cCoDytDjU/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=p-cCoDytDjU" }],
        commentary:
          "TIMBA. La respuesta habanera de los noventa: metales de conservatorio y velocidad rítmica brutal. José Luis 'El Tosco' Cortés acuñó el término y esta es su tesis doctoral bailable, en pleno Período Especial.",
      },
      {
        kind: "track",
        rank: 1,
        artist: "Cali Flow Latino",
        title: "Ras Tas Tas",
        year: 2014,
        imageUrl: "https://i.ytimg.com/vi/su5Cnj6Ai60/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=su5Cnj6Ai60" }],
        commentary:
          "SALSA CHOKE. Nacida en Tumaco hacia 2008, salsa cruzada con ritmos urbanos del Pacífico colombiano. La selección Colombia la bailó en cada gol del Mundial 2014 y convirtió este corte caleño en fenómeno global.",
      },
    ],
    footnotes: [],
  },

  {
    id: "li-nn-boogaloo",
    partnerId: "pa-noche-negra",
    slug: "cinco-canonazos-boogaloo-descarga",
    type: "listicle",
    title: "5 cañonazos de boogaloo y descarga",
    subtitle: "Nueva York, años sesenta: cuando la salsa hablaba spanglish",
    excerpt:
      "Antes de que Fania industrializara la salsa, el Barrio bailaba boogaloo: R&B con congas, coros en spanglish y piano de fiesta. Cinco cortes esenciales — y la descarga cubana que los hizo posibles.",
    vibeMin: 5, vibeMax: 7,
    genres: ["salsa", "latin-jazz"],
    tags: ["dancefloor"],
    imageUrl: "/flyers/nn-li-boogaloo.jpg",
    publishedAt: "2026-04-15T11:00:00",
    date: "2026-04-15T11:00:00",
    author: "Carlos René",
    artists: ["Joe Cuba", "Pete Rodríguez", "Ray Barretto", "Héctor Rivera", "Cachao"],
    articleBody: [
      {
        kind: "lede",
        text: "El boogaloo duró un suspiro — del 66 al 69, apenas — pero dejó más cañonazos por minuto que casi cualquier género. Cinco piezas para entender por qué el Barrio nunca lo superó del todo.",
      },
      { kind: "divider" },
      {
        kind: "track",
        rank: 5,
        artist: "Cachao y su Ritmo Caliente",
        title: "Descarga Cubana",
        year: 1957,
        imageUrl: "https://i.ytimg.com/vi/P61p-wEwdPQ/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=P61p-wEwdPQ" }],
        commentary:
          "El origen de todo: grabada en los estudios Panart de La Habana en sesiones que empezaban a las 4 AM, después de los shows de cabaret. El disco vendió más de un millón de copias y es el plano de toda descarga posterior.",
      },
      {
        kind: "track",
        rank: 4,
        artist: "Ray Barretto y Su Charanga Moderna",
        title: "El Watusi",
        year: 1962,
        imageUrl: "https://i.ytimg.com/vi/e3IC4yr5ilM/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=e3IC4yr5ilM" }],
        commentary:
          "Presunción callejera hablada sobre un vamp hipnótico de charanga: el crossover latino más exitoso de la era pachanga en Billboard, y la plantilla que el boogaloo industrializaría cuatro años después.",
      },
      {
        kind: "track",
        rank: 3,
        artist: "Héctor Rivera",
        title: "At the Party",
        year: 1966,
        imageUrl: "https://i.ytimg.com/vi/U770MisAEEY/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=U770MisAEEY" }],
        commentary:
          "El corte titular de su debut en el diminuto sello Barry: latin soul sin pausas que sigue siendo básico igual en las pistas de northern soul británico que en cualquier fiesta de 45s que se respete.",
      },
      {
        kind: "track",
        rank: 2,
        artist: "Pete Rodríguez",
        title: "I Like It Like That",
        year: 1967,
        imageUrl: "https://i.ytimg.com/vi/DEjN42FW2sU/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=DEjN42FW2sU" }],
        commentary:
          "El riff de piano descendente más contagioso del género, directo al Billboard nacional. Medio siglo después, Cardi B, Bad Bunny y J Balvin lo interpolaron en 'I Like It' — el boogaloo cobra regalías desde el más allá.",
      },
      {
        kind: "track",
        rank: 1,
        artist: "Joe Cuba Sextette",
        title: "Bang! Bang!",
        year: 1966,
        imageUrl: "https://i.ytimg.com/vi/9SMJq2m1BPg/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=9SMJq2m1BPg" }],
        commentary:
          "El hit de boogaloo más grande de los sesenta: más de un millón de copias en 1966. Escrito por Joe Cuba con el timbalero y cantante Jimmy Sabater — el momento exacto en que el R&B y la clave firmaron la paz.",
      },
    ],
    footnotes: [],
  },

  {
    id: "li-nn-cumbias-salon",
    partnerId: "pa-noche-negra",
    slug: "cinco-cumbias-que-llenan-el-salon",
    type: "listicle",
    title: "5 cumbias que llenan el salón",
    subtitle: "Del Amazonas a Tepito: el canon sonidero",
    excerpt:
      "Las piezas que ningún sonidero puede no llevar: cumbia amazónica, acordeón sabanero, saxofón fronterizo y sintetizador poblano. Cinco cumbias con las que la duela nunca falla.",
    vibeMin: 5, vibeMax: 8,
    genres: ["cumbia", "cumbia-sonidera", "sonidero"],
    tags: ["dancefloor", "soundsystem", "sala-grande"],
    imageUrl: "/flyers/nn-li-sonidero.jpg",
    publishedAt: "2026-08-08T11:00:00",
    date: "2026-08-08T11:00:00",
    author: "Redacción Gradiente",
    artists: ["Los Mirlos", "Celso Piña", "Aniceto Molina", "Fito Olivares", "Grupo Soñador"],
    articleBody: [
      {
        kind: "lede",
        text: "La leyenda dice que la rebajada nació en Monterrey de una tornamesa descompuesta que tocaba lento — y que Sonido Dueñez decidió que así sonaba mejor. Verdad o mito, el canon sonidero se construyó de préstamos: cumbias peruanas, colombianas y texanas que México hizo suyas a fuerza de bocina. Estas cinco nunca fallan.",
      },
      { kind: "divider" },
      {
        kind: "track",
        rank: 5,
        artist: "Los Mirlos",
        title: "La Danza de los Mirlos",
        year: 1973,
        imageUrl: "https://i.ytimg.com/vi/kAap4MCq6WY/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=kAap4MCq6WY" }],
        commentary:
          "Cumbia amazónica de Moyobamba, Perú (sello Infopesa): el riff de guitarra serpenteante que los sonideros mexicanos adoptaron como himno propio. La remasterización oficial la empareja con 'Cumbia de los Pajaritos' — doble regalo.",
      },
      {
        kind: "track",
        rank: 4,
        artist: "Aniceto Molina",
        title: "La Cumbia Sampuesana",
        imageUrl: "https://i.ytimg.com/vi/_VVVMHx4vec/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=_VVVMHx4vec" }],
        commentary:
          "El Tigre Sabanero vivió en CDMX de 1973 a 1984 y en esos años metió el acordeón de Sampués al canon capitalino para siempre. La versión que México conoce es la suya — y la que el salón corea completa.",
      },
      {
        kind: "track",
        rank: 3,
        artist: "Fito Olivares y Su Grupo",
        title: "Juana la Cubana",
        year: 1986,
        imageUrl: "https://i.ytimg.com/vi/n2ZHYul066M/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=n2ZHYul066M" }],
        commentary:
          "El saxofón del circuito Tamaulipas-Texas convertido en obligación nacional: no existe quinceañera, boda ni salón donde Juana no aparezca. Cumbia fronteriza en estado puro.",
      },
      {
        kind: "track",
        rank: 2,
        artist: "Celso Piña (feat. Control Machete & Blanquito Man)",
        title: "Cumbia Sobre el Río",
        year: 2001,
        imageUrl: "https://i.ytimg.com/vi/Bbl_xc2Mk0c/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=Bbl_xc2Mk0c" }],
        commentary:
          "El Rebelde del Acordeón fundió la colombia regia con el hip-hop de Control Machete y llevó la cultura de bocina de la Campana a la radio nacional. El puente entre el sonidero y todo lo demás.",
      },
      {
        kind: "track",
        rank: 1,
        artist: "Grupo Soñador",
        title: "El Paso del Gigante",
        year: 2001,
        imageUrl: "https://i.ytimg.com/vi/UzUAc2MIsHA/hqdefault.jpg",
        embeds: [{ platform: "youtube", url: "https://www.youtube.com/watch?v=UzUAc2MIsHA" }],
        commentary:
          "El himno del sintetizador poblano — originalmente 'El Gigante de Hierro', según su compositor Beto Tlahuetl — que explotó por el universo sonidero y mandó a la banda de Cholula a giras agotadas por Estados Unidos. Cuando entra, la duela tiembla.",
      },
    ],
    footnotes: [],
  },
];

export const NOCHE_NEGRA_PARTNER: ContentItem = {
    // Dev-seed mirror of the prod partner row (same id/slug/logo path), so
    // the /mapa focus + marketplace demo work against the mock dataset.
    id: "pa-noche-negra",
    slug: "noche-negra",
    type: "partner",
    title: "Noche Negra",
    subtitle: "Colectivo · Vinyl Only · CDMX",
    vibeMin: 4, vibeMax: 8,
    genres: [],
    tags: [],
    imageUrl: "/partners/noche-negra.jpg",
    publishedAt: "2026-07-25T12:00:00",
    partnerKind: "promoter",
    partnerUrl: "https://www.instagram.com/nochenegra.mx/",
    // Real socials (obi icon row) — IG + FB confirmed; nothing invented.
    links: [
      { label: "Instagram", url: "https://www.instagram.com/nochenegra.mx/" },
      { label: "Facebook", url: "https://www.facebook.com/nochenegramx" },
    ],
    partnerLastUpdated: "2026-07-25T12:00:00",
    marketplaceEnabled: true,
    marketplaceDescription:
      "La mesa de discos del colectivo, ahora en línea: tornamesas Technics revisadas por nuestro técnico de confianza, cápsulas y agujas Shure de la era dorada (descontinuadas desde 2018 — lo que hay es lo que hay) y adaptadores de 45 para que tus sietes giren como deben. Recogida en nuestras fiestas o envío a todo México.",
    marketplaceLocation: "CDMX, MX",
    marketplaceCurrency: "MXN",
    marketplaceListings: [
      {
        id: "mkl-nn-01",
        title: "Technics SL-1200MK2 (plata)",
        category: "turntable",
        subcategory: "Direct Drive",
        price: 12000,
        condition: "VG+",
        images: ["/flyers/nn-mkt-1200mk2.jpg", "/flyers/nn-mkt-1200mk2-b.jpg"],
        status: "available",
        tags: ["quartz-lock", "servida", "clasica"],
        shippingMode: "local",
        description:
          "La tornamesa que definió el oficio: tracción directa quartz-lock, torque instantáneo y pitch de ±8%. Producida de 1979 a 2010 — más de tres millones de unidades de la serie vendidas y contando. Esta unidad viene revisada: tonearm calibrado, RCA nuevos, luz de aguja funcionando. Sin cápsula.",
        publishedAt: "2026-07-20T10:00:00",
      },
      {
        id: "mkl-nn-02",
        title: "Technics SL-1210MK2 (negra)",
        category: "turntable",
        subcategory: "Direct Drive",
        price: 14500,
        condition: "VG+",
        images: ["/flyers/nn-mkt-1210.jpg"],
        status: "available",
        tags: ["cabina", "clasica"],
        shippingMode: "local",
        description:
          "Mecánicamente idéntica a la 1200MK2 — misma corrida 1979-2010 — pero en el acabado negro mate que es la firma visual de toda cabina seria. Detalles cosméticos menores en la base, funcionamiento impecable.",
        publishedAt: "2026-07-18T10:00:00",
      },
      {
        id: "mkl-nn-03",
        title: "Technics SL-1200MK5",
        category: "turntable",
        subcategory: "Direct Drive",
        price: 18000,
        condition: "NM",
        images: ["/flyers/nn-mkt-mk5.jpg"],
        status: "reserved",
        tags: ["ultima-era", "coleccion"],
        shippingMode: "both",
        description:
          "La última revisión clásica de amplia distribución antes del cierre de 2010: anti-skating extendido y dos décadas menos de uso que cualquier MK2 temprana. Ejemplar casi mint, un solo dueño, con tapa.",
        publishedAt: "2026-07-15T10:00:00",
      },
      {
        id: "mkl-nn-04",
        title: "Shure M44-7 — cápsula de batalla",
        category: "turntable",
        subcategory: "Cartridge",
        price: 6000,
        condition: "VG+",
        images: ["/flyers/nn-mkt-shure.jpg"],
        status: "available",
        tags: ["descontinuada", "skip-resistance", "m44"],
        shippingMode: "both",
        description:
          "La cápsula estándar de batalla: resistencia al salto legendaria y desgaste mínimo del disco. Shure cerró su línea fonográfica entera en 2018 después de 86 años — desde entonces los precios se triplicaron y cada M44-7 viva es patrimonio. Cuerpo en excelente estado, aguja con vida útil amplia. (Foto de referencia: cuerpo de la familia M44.)",
        publishedAt: "2026-07-12T10:00:00",
      },
      {
        id: "mkl-nn-05",
        title: "Shure N44-7 — aguja de repuesto (NOS)",
        category: "turntable",
        subcategory: "Cartridge",
        price: 2800,
        condition: "NEW",
        images: ["/flyers/nn-mkt-shure-b.jpg"],
        status: "available",
        tags: ["nos", "sellada", "m44"],
        shippingMode: "both",
        description:
          "Repuesto genuino Shure para el cuerpo M44-7, nuevo de stock antiguo y sellado. Descontinuado con toda la línea en 2018: existen repuestos aftermarket (JICO, Tonar) pero el original es otra cosa. Para la cápsula que ya tienes o la que te vas a llevar de esta misma mesa.",
        publishedAt: "2026-07-12T10:00:00",
      },
      {
        id: "mkl-nn-06",
        title: "Adaptador 45 Technics original (SFWE010)",
        category: "other",
        price: 700,
        condition: "NEW",
        images: ["/flyers/nn-mkt-45puck.jpg"],
        status: "available",
        tags: ["45s", "refaccion-original"],
        shippingMode: "both",
        description:
          "El puck clásico de cabina: la refacción genuina Technics para la serie SL-1200. La mayoría de las tornamesas usadas perdieron el suyo hace décadas — por eso el original se cotiza. Nuevo, en bolsa.",
        publishedAt: "2026-07-08T10:00:00",
      },
      {
        id: "mkl-nn-07",
        title: "Mukatsuku — par de adaptadores 45 de acero (domo pesado)",
        category: "other",
        price: 680,
        condition: "NEW",
        images: ["/flyers/nn-mkt-45steel.jpg"],
        status: "available",
        tags: ["45s", "acero", "juno-exclusive"],
        shippingMode: "both",
        description:
          "Par de adaptadores de acero inoxidable maquinados de precisión del sello británico de 45s Mukatsuku (exclusiva de Juno), grabados a láser. El peso del domo (185 g) funciona además como mini estabilizador del disco. El adaptador que se queda puesto cuando levantas el siete.",
        publishedAt: "2026-07-05T10:00:00",
      },
      {
        id: "mkl-nn-08",
        title: "Lote: adaptador bullet vintage + inserts",
        category: "other",
        price: 250,
        condition: "VG",
        images: ["/flyers/nn-mkt-45bullet.jpg", "/flyers/nn-mkt-45insert.jpg"],
        status: "sold",
        tags: ["45s", "vintage", "lote"],
        shippingMode: "local",
        description:
          "Lote de arqueología del 45: un adaptador tipo bullet de época (de los que se enroscaban al eje de las consolas) más un puñado de inserts snap-in de plástico. Para el que dedica su repisa a la historia del formato.",
        publishedAt: "2026-06-28T10:00:00",
      },
    ],
};

// Content first, identity row last — spread order mirrors the
// items-then-partners layout of lib/mockData.ts.
export const NOCHE_NEGRA_SEED: ContentItem[] = [
  ...NOCHE_NEGRA_ITEMS,
  NOCHE_NEGRA_PARTNER,
];
