// ============================================================================
// scripts/applyPartnerLogos.ts — point partner image_url at the static logos
// ============================================================================
// Reconciles `items.image_url` (type='partner') with the version-controlled
// logo files in public/partners/. That directory is the single source of
// truth: for every `<slug>.<ext>` file there, the matching partner's image_url
// is set to `/partners/<slug>.<ext>` (served by Vercel from public/).
//
// Two phases:
//   1. (always) regenerate supabase/migrations/0032_partner_logos.sql from the
//      directory — the version-controlled record of the prod change.
//   2. (only with --apply) write those values to prod via the service-role
//      client. Run this ONLY AFTER the static files have deployed, otherwise
//      the live site points at logos that 404 until the next deploy.
//
// Usage:
//   npx tsx scripts/applyPartnerLogos.ts            # regenerate the .sql only
//   npx tsx scripts/applyPartnerLogos.ts --apply    # ...and write to prod
//
// Idempotent: plain UPDATEs keyed on slug; re-running converges. Partners with
// no file (passline-promo on /flyers/, and the still-unsourced ones) are left
// untouched. Requires .env.local with the service-role key.
// ============================================================================

import { config } from 'dotenv'
import { createClient } from '@supabase/supabase-js'
import { readdirSync, writeFileSync } from 'node:fs'
import { resolve, join, parse } from 'node:path'

config({ path: resolve(process.cwd(), '.env.local') })

const PARTNERS_DIR = resolve(process.cwd(), 'public', 'partners')
const MIGRATION = resolve(process.cwd(), 'supabase', 'migrations', '0032_partner_logos.sql')

// slug -> "/partners/<file>", derived from the committed files.
const map = readdirSync(PARTNERS_DIR)
  .filter((f) => /\.(jpg|jpeg|png|webp|svg|gif)$/i.test(f))
  .sort()
  .map((file) => ({ slug: parse(file).name.toLowerCase(), url: `/partners/${file}` }))

// ── Phase 1: (re)generate the migration ─────────────────────────────────────
const header = `-- 0032_partner_logos.sql
-- Repoint partner image_url at the version-controlled static logos in
-- public/partners/ (the single source of truth). GENERATED by
-- scripts/applyPartnerLogos.ts from that directory — do not hand-edit; re-run
-- the script instead. Idempotent: plain UPDATEs keyed on slug.
--
-- Context: 0031 carries /partners/ paths for the logos that existed when it
-- was written, but it is ON CONFLICT DO NOTHING and the rows were already
-- seeded, so those values never reached prod. This migration UPDATEs image_url
-- for every partner that now has a file in public/partners/ (${map.length} total).
`
const body = map
  .map((m) => `update public.items set image_url = '${m.url}' where slug = '${m.slug}' and type = 'partner';`)
  .join('\n')
writeFileSync(MIGRATION, `${header}\n${body}\n`)
console.log(`Wrote ${MIGRATION} (${map.length} partners)`)

// ── Phase 2: apply to prod (guarded) ────────────────────────────────────────
if (!process.argv.includes('--apply')) {
  console.log('Dry run (migration written only). Re-run with --apply after deploy to write prod.')
  process.exit(0)
}

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY
if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local')
  process.exit(1)
}
const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
})

async function apply() {
  let ok = 0
  let failed = 0
  for (const m of map) {
    const { error, count } = await supabase
      .from('items')
      .update({ image_url: m.url }, { count: 'exact' })
      .eq('slug', m.slug)
      .eq('type', 'partner')
    if (error) {
      console.log(`FAIL ${m.slug} — ${error.message}`)
      failed++
    } else if (!count) {
      console.log(`MISS ${m.slug} — no matching partner row`)
    } else {
      ok++
    }
  }
  console.log(`\nApplied. updated=${ok} failed=${failed} of ${map.length}`)
}

apply().catch((e) => {
  console.error(e)
  process.exit(1)
})
