-- 0032_partner_logos.sql
-- Repoint partner image_url at the version-controlled static logos in
-- public/partners/ (the single source of truth). GENERATED by
-- scripts/applyPartnerLogos.ts from that directory — do not hand-edit; re-run
-- the script instead. Idempotent: plain UPDATEs keyed on slug.
--
-- Context: 0031 carries /partners/ paths for the logos that existed when it
-- was written, but it is ON CONFLICT DO NOTHING and the rows were already
-- seeded, so those values never reached prod. This migration UPDATEs image_url
-- for every partner that now has a file in public/partners/ (62 total).

update public.items set image_url = '/partners/abditorymexico.jpg' where slug = 'abditorymexico' and type = 'partner';
update public.items set image_url = '/partners/amigos-de-amigos.jpg' where slug = 'amigos-de-amigos' and type = 'partner';
update public.items set image_url = '/partners/antimateria-sonora.jpg' where slug = 'antimateria-sonora' and type = 'partner';
update public.items set image_url = '/partners/artistas-desconocidos.jpg' where slug = 'artistas-desconocidos' and type = 'partner';
update public.items set image_url = '/partners/avant-garde-institute.jpg' where slug = 'avant-garde-institute' and type = 'partner';
update public.items set image_url = '/partners/brutal-mx.jpg' where slug = 'brutal-mx' and type = 'partner';
update public.items set image_url = '/partners/caliente-mex.jpg' where slug = 'caliente-mex' and type = 'partner';
update public.items set image_url = '/partners/capricho.jpg' where slug = 'capricho' and type = 'partner';
update public.items set image_url = '/partners/casa-del-lago.jpg' where slug = 'casa-del-lago' and type = 'partner';
update public.items set image_url = '/partners/cjantal.jpg' where slug = 'cjantal' and type = 'partner';
update public.items set image_url = '/partners/clima-calido.jpg' where slug = 'clima-calido' and type = 'partner';
update public.items set image_url = '/partners/club-japan.jpg' where slug = 'club-japan' and type = 'partner';
update public.items set image_url = '/partners/cuatro-cuartos-bestial-crew.jpg' where slug = 'cuatro-cuartos-bestial-crew' and type = 'partner';
update public.items set image_url = '/partners/dark-side-records-mx.jpg' where slug = 'dark-side-records-mx' and type = 'partner';
update public.items set image_url = '/partners/deposito-sonoro.jpg' where slug = 'deposito-sonoro' and type = 'partner';
update public.items set image_url = '/partners/disco-esencia.jpg' where slug = 'disco-esencia' and type = 'partner';
update public.items set image_url = '/partners/duro.jpg' where slug = 'duro' and type = 'partner';
update public.items set image_url = '/partners/encarta-97.jpg' where slug = 'encarta-97' and type = 'partner';
update public.items set image_url = '/partners/ephemera.jpg' where slug = 'ephemera' and type = 'partner';
update public.items set image_url = '/partners/fascinoma.png' where slug = 'fascinoma' and type = 'partner';
update public.items set image_url = '/partners/fhauna.jpg' where slug = 'fhauna' and type = 'partner';
update public.items set image_url = '/partners/funk.jpg' where slug = 'funk' and type = 'partner';
update public.items set image_url = '/partners/hola-wave.jpg' where slug = 'hola-wave' and type = 'partner';
update public.items set image_url = '/partners/honest-allies.jpg' where slug = 'honest-allies' and type = 'partner';
update public.items set image_url = '/partners/hot-cakes.png' where slug = 'hot-cakes' and type = 'partner';
update public.items set image_url = '/partners/infinite-machine.jpg' where slug = 'infinite-machine' and type = 'partner';
update public.items set image_url = '/partners/jungle-empire.jpg' where slug = 'jungle-empire' and type = 'partner';
update public.items set image_url = '/partners/las-clementinas.jpg' where slug = 'las-clementinas' and type = 'partner';
update public.items set image_url = '/partners/lichi.jpg' where slug = 'lichi' and type = 'partner';
update public.items set image_url = '/partners/loose-blues.jpg' where slug = 'loose-blues' and type = 'partner';
update public.items set image_url = '/partners/low-freq-mx.jpg' where slug = 'low-freq-mx' and type = 'partner';
update public.items set image_url = '/partners/maad-store.jpg' where slug = 'maad-store' and type = 'partner';
update public.items set image_url = '/partners/makossa-disco.jpg' where slug = 'makossa-disco' and type = 'partner';
update public.items set image_url = '/partners/maquina-simple-ediciones.jpg' where slug = 'maquina-simple-ediciones' and type = 'partner';
update public.items set image_url = '/partners/maricas-records.jpg' where slug = 'maricas-records' and type = 'partner';
update public.items set image_url = '/partners/meditatio-sonus.jpg' where slug = 'meditatio-sonus' and type = 'partner';
update public.items set image_url = '/partners/melodykrafter.jpg' where slug = 'melodykrafter' and type = 'partner';
update public.items set image_url = '/partners/mental.jpg' where slug = 'mental' and type = 'partner';
update public.items set image_url = '/partners/mixtlan.jpg' where slug = 'mixtlan' and type = 'partner';
update public.items set image_url = '/partners/mwamwa.jpg' where slug = 'mwamwa' and type = 'partner';
update public.items set image_url = '/partners/noche-negra.jpg' where slug = 'noche-negra' and type = 'partner';
update public.items set image_url = '/partners/profundo.png' where slug = 'profundo' and type = 'partner';
update public.items set image_url = '/partners/rat-back-crew.jpg' where slug = 'rat-back-crew' and type = 'partner';
update public.items set image_url = '/partners/raxtion-music.jpg' where slug = 'raxtion-music' and type = 'partner';
update public.items set image_url = '/partners/reflejo.png' where slug = 'reflejo' and type = 'partner';
update public.items set image_url = '/partners/rei-room.jpg' where slug = 'rei-room' and type = 'partner';
update public.items set image_url = '/partners/relink-data.jpg' where slug = 'relink-data' and type = 'partner';
update public.items set image_url = '/partners/revancha.svg' where slug = 'revancha' and type = 'partner';
update public.items set image_url = '/partners/rey-vinilo.jpg' where slug = 'rey-vinilo' and type = 'partner';
update public.items set image_url = '/partners/saundo.jpg' where slug = 'saundo' and type = 'partner';
update public.items set image_url = '/partners/sin-ap-sis.jpg' where slug = 'sin-ap-sis' and type = 'partner';
update public.items set image_url = '/partners/sonidero-sabotaje.jpg' where slug = 'sonidero-sabotaje' and type = 'partner';
update public.items set image_url = '/partners/ssensorial.jpg' where slug = 'ssensorial' and type = 'partner';
update public.items set image_url = '/partners/ten-toes.jpg' where slug = 'ten-toes' and type = 'partner';
update public.items set image_url = '/partners/tra-tra.jpg' where slug = 'tra-tra' and type = 'partner';
update public.items set image_url = '/partners/tumba-7.jpg' where slug = 'tumba-7' and type = 'partner';
update public.items set image_url = '/partners/uauh.jpg' where slug = 'uauh' and type = 'partner';
update public.items set image_url = '/partners/ufo-camp.jpg' where slug = 'ufo-camp' and type = 'partner';
update public.items set image_url = '/partners/ultradisko.jpg' where slug = 'ultradisko' and type = 'partner';
update public.items set image_url = '/partners/vaneechi.jpg' where slug = 'vaneechi' and type = 'partner';
update public.items set image_url = '/partners/winona.jpg' where slug = 'winona' and type = 'partner';
update public.items set image_url = '/partners/wvwv.jpg' where slug = 'wvwv' and type = 'partner';
